// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.12.0
//   protoc               unknown
// source: steemvm/steembridge/v1/asset.proto

/* eslint-disable */

export const protobufPackage = "steemvm.steembridge.v1";

/**
 * BridgeAsset identifies which native Steem asset a deposit/withdrawal moves.
 * The zero value is STEEM, so pre-existing records and messages default to STEEM.
 */
export enum BridgeAsset {
  BRIDGE_ASSET_STEEM = 0,
  BRIDGE_ASSET_SBD = 1,
}

export function bridgeAssetFromJSON(object: any): BridgeAsset {
  switch (object) {
    case 0:
    case "BRIDGE_ASSET_STEEM":
      return BridgeAsset.BRIDGE_ASSET_STEEM;
    case 1:
    case "BRIDGE_ASSET_SBD":
      return BridgeAsset.BRIDGE_ASSET_SBD;
    default:
      throw new globalThis.Error("Unrecognized enum value " + object + " for enum BridgeAsset");
  }
}

export function bridgeAssetToJSON(object: BridgeAsset): string {
  switch (object) {
    case BridgeAsset.BRIDGE_ASSET_STEEM:
      return "BRIDGE_ASSET_STEEM";
    case BridgeAsset.BRIDGE_ASSET_SBD:
      return "BRIDGE_ASSET_SBD";
    default:
      throw new globalThis.Error("Unrecognized enum value " + object + " for enum BridgeAsset");
  }
}
