// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: steemvm/steembridge/v1/genesis.proto

package types

import (
	cosmossdk_io_math "cosmossdk.io/math"
	fmt "fmt"
	_ "github.com/cosmos/cosmos-sdk/types/tx/amino"
	_ "github.com/cosmos/gogoproto/gogoproto"
	proto "github.com/cosmos/gogoproto/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// GenesisState defines the steembridge module's genesis state.
type GenesisState struct {
	// params defines all the parameters of the module.
	Params          Params       `protobuf:"bytes,1,opt,name=params,proto3" json:"params"`
	DepositList     []Deposit    `protobuf:"bytes,2,rep,name=deposit_list,json=depositList,proto3" json:"deposit_list"`
	DepositCount    uint64       `protobuf:"varint,3,opt,name=deposit_count,json=depositCount,proto3" json:"deposit_count,omitempty"`
	WithdrawalList  []Withdrawal `protobuf:"bytes,4,rep,name=withdrawal_list,json=withdrawalList,proto3" json:"withdrawal_list"`
	WithdrawalCount uint64       `protobuf:"varint,5,opt,name=withdrawal_count,json=withdrawalCount,proto3" json:"withdrawal_count,omitempty"`
	// total_minted_asteem is the cumulative amount of asteem minted by bridge-in deposits.
	TotalMintedAsteem cosmossdk_io_math.Int `protobuf:"bytes,6,opt,name=total_minted_asteem,json=totalMintedAsteem,proto3,customtype=cosmossdk.io/math.Int" json:"total_minted_asteem"`
	// total_burned_asteem is the cumulative amount of asteem burned by bridge-out withdrawals.
	TotalBurnedAsteem     cosmossdk_io_math.Int `protobuf:"bytes,7,opt,name=total_burned_asteem,json=totalBurnedAsteem,proto3,customtype=cosmossdk.io/math.Int" json:"total_burned_asteem"`
	NameRegistrationList  []NameRegistration    `protobuf:"bytes,8,rep,name=name_registration_list,json=nameRegistrationList,proto3" json:"name_registration_list"`
	NameRegistrationCount uint64                `protobuf:"varint,9,opt,name=name_registration_count,json=nameRegistrationCount,proto3" json:"name_registration_count,omitempty"`
	ActiveNameList        []NameRecord          `protobuf:"bytes,10,rep,name=active_name_list,json=activeNameList,proto3" json:"active_name_list"`
}

func (m *GenesisState) Reset()         { *m = GenesisState{} }
func (m *GenesisState) String() string { return proto.CompactTextString(m) }
func (*GenesisState) ProtoMessage()    {}
func (*GenesisState) Descriptor() ([]byte, []int) {
	return fileDescriptor_2fb668670f8f6ef9, []int{0}
}
func (m *GenesisState) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *GenesisState) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_GenesisState.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *GenesisState) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GenesisState.Merge(m, src)
}
func (m *GenesisState) XXX_Size() int {
	return m.Size()
}
func (m *GenesisState) XXX_DiscardUnknown() {
	xxx_messageInfo_GenesisState.DiscardUnknown(m)
}

var xxx_messageInfo_GenesisState proto.InternalMessageInfo

func (m *GenesisState) GetParams() Params {
	if m != nil {
		return m.Params
	}
	return Params{}
}

func (m *GenesisState) GetDepositList() []Deposit {
	if m != nil {
		return m.DepositList
	}
	return nil
}

func (m *GenesisState) GetDepositCount() uint64 {
	if m != nil {
		return m.DepositCount
	}
	return 0
}

func (m *GenesisState) GetWithdrawalList() []Withdrawal {
	if m != nil {
		return m.WithdrawalList
	}
	return nil
}

func (m *GenesisState) GetWithdrawalCount() uint64 {
	if m != nil {
		return m.WithdrawalCount
	}
	return 0
}

func (m *GenesisState) GetNameRegistrationList() []NameRegistration {
	if m != nil {
		return m.NameRegistrationList
	}
	return nil
}

func (m *GenesisState) GetNameRegistrationCount() uint64 {
	if m != nil {
		return m.NameRegistrationCount
	}
	return 0
}

func (m *GenesisState) GetActiveNameList() []NameRecord {
	if m != nil {
		return m.ActiveNameList
	}
	return nil
}

func init() {
	proto.RegisterType((*GenesisState)(nil), "steemvm.steembridge.v1.GenesisState")
}

func init() {
	proto.RegisterFile("steemvm/steembridge/v1/genesis.proto", fileDescriptor_2fb668670f8f6ef9)
}

var fileDescriptor_2fb668670f8f6ef9 = []byte{
	// 500 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x93, 0xc1, 0x6e, 0xd3, 0x4c,
	0x14, 0x85, 0xe3, 0xbf, 0x69, 0x7e, 0x32, 0x29, 0xd0, 0x9a, 0xb6, 0x44, 0x91, 0xea, 0x44, 0x2d,
	0x12, 0x86, 0x85, 0xad, 0x16, 0x09, 0xd6, 0x35, 0x48, 0x80, 0x44, 0x11, 0x98, 0x05, 0x12, 0x1b,
	0x6b, 0x62, 0x8f, 0xdc, 0x11, 0x99, 0x99, 0x68, 0xe6, 0x36, 0x85, 0xb7, 0xe0, 0x31, 0x58, 0xf2,
	0x18, 0x5d, 0xa1, 0x2e, 0x11, 0x8b, 0x0a, 0x25, 0x0b, 0x5e, 0x03, 0xf9, 0xce, 0x84, 0x44, 0x2d,
	0x46, 0x6c, 0x12, 0xeb, 0xea, 0x9c, 0xef, 0xdc, 0x39, 0xf6, 0x90, 0x3b, 0x06, 0x18, 0x13, 0x13,
	0x11, 0xe3, 0xff, 0x50, 0xf3, 0xa2, 0x64, 0xf1, 0x64, 0x3f, 0x2e, 0x99, 0x64, 0x86, 0x9b, 0x68,
	0xac, 0x15, 0x28, 0x7f, 0xdb, 0xa9, 0xa2, 0x25, 0x55, 0x34, 0xd9, 0xef, 0x6d, 0x50, 0xc1, 0xa5,
	0x8a, 0xf1, 0xd7, 0x4a, 0x7b, 0x9b, 0xa5, 0x2a, 0x15, 0x3e, 0xc6, 0xd5, 0x93, 0x9b, 0xd6, 0xc5,
	0x14, 0x6c, 0xac, 0x0c, 0x07, 0xa7, 0x8a, 0x6a, 0x54, 0x92, 0x0a, 0x96, 0x69, 0x56, 0x72, 0x03,
	0x9a, 0x02, 0x57, 0xd2, 0xe9, 0xf7, 0x6a, 0xf4, 0x63, 0xaa, 0xa9, 0x70, 0xbb, 0xf7, 0xee, 0xd6,
	0x88, 0x4e, 0x39, 0x1c, 0x17, 0x9a, 0x9e, 0xd2, 0x91, 0x15, 0xee, 0x7e, 0x5d, 0x25, 0x6b, 0x4f,
	0xed, 0xb1, 0xdf, 0x00, 0x05, 0xe6, 0x1f, 0x92, 0x96, 0x25, 0x75, 0xbd, 0x81, 0x17, 0x76, 0x0e,
	0x82, 0xe8, 0xcf, 0x35, 0x44, 0xaf, 0x50, 0x95, 0xb4, 0xcf, 0x2e, 0xfa, 0x8d, 0xcf, 0x3f, 0xbf,
	0xdc, 0xf7, 0x52, 0x67, 0xf4, 0x9f, 0x91, 0x35, 0x77, 0xc4, 0x6c, 0xc4, 0x0d, 0x74, 0xff, 0x1b,
	0xac, 0x84, 0x9d, 0x83, 0x7e, 0x1d, 0xe8, 0x89, 0xd5, 0x26, 0xcd, 0x8a, 0x94, 0x76, 0x9c, 0xf5,
	0x05, 0x37, 0xe0, 0xef, 0x91, 0xeb, 0x73, 0x52, 0xae, 0x4e, 0x24, 0x74, 0x57, 0x06, 0x5e, 0xd8,
	0x4c, 0xe7, 0xf8, 0xc7, 0xd5, 0xcc, 0x7f, 0x4d, 0x6e, 0x2e, 0x8e, 0x65, 0x13, 0x9b, 0x98, 0xb8,
	0x5b, 0x97, 0xf8, 0xf6, 0xb7, 0xdc, 0x85, 0xde, 0x58, 0x00, 0x30, 0xf7, 0x1e, 0x59, 0x5f, 0x42,
	0xda, 0xe8, 0x55, 0x8c, 0x5e, 0x8a, 0xb2, 0xe9, 0x47, 0xe4, 0x16, 0x28, 0xa0, 0xa3, 0x4c, 0x70,
	0x09, 0xac, 0xc8, 0x28, 0x66, 0x75, 0x5b, 0x03, 0x2f, 0x6c, 0x27, 0x3b, 0x15, 0xfd, 0xfb, 0x45,
	0x7f, 0x2b, 0x57, 0x46, 0x28, 0x63, 0x8a, 0xf7, 0x11, 0x57, 0xb1, 0xa0, 0x70, 0x1c, 0x3d, 0x97,
	0x90, 0x6e, 0xa0, 0xf3, 0x08, 0x8d, 0x87, 0xe8, 0x5b, 0xe0, 0x86, 0x27, 0x5a, 0x2e, 0x70, 0xff,
	0xff, 0x3b, 0x2e, 0x41, 0xa3, 0xc3, 0x15, 0x64, 0xfb, 0xca, 0x77, 0x64, 0x2b, 0xba, 0x86, 0x15,
	0x85, 0x75, 0x15, 0xbd, 0xa4, 0x82, 0xa5, 0x4b, 0x26, 0x57, 0xd4, 0xa6, 0xbc, 0x34, 0xc7, 0xba,
	0x1e, 0x92, 0xdb, 0x57, 0x53, 0x6c, 0x6b, 0x6d, 0x6c, 0x6d, 0xeb, 0xb2, 0xcd, 0x76, 0x97, 0x92,
	0x75, 0x9a, 0x03, 0x9f, 0xb0, 0x0c, 0xed, 0xb8, 0x17, 0xf9, 0xfb, 0xab, 0xb3, 0x7b, 0xe5, 0x4a,
	0x17, 0xf3, 0x57, 0x67, 0x09, 0xd5, 0xbc, 0xda, 0x25, 0x79, 0x74, 0x36, 0x0d, 0xbc, 0xf3, 0x69,
	0xe0, 0xfd, 0x98, 0x06, 0xde, 0xa7, 0x59, 0xd0, 0x38, 0x9f, 0x05, 0x8d, 0x6f, 0xb3, 0xa0, 0xf1,
	0x6e, 0x67, 0x7e, 0x27, 0x3e, 0xc4, 0x4a, 0xd3, 0x7c, 0xc4, 0x62, 0x77, 0x2f, 0xe0, 0xe3, 0x98,
	0x99, 0x61, 0x0b, 0x2f, 0xc4, 0x83, 0x5f, 0x01, 0x00, 0x00, 0xff, 0xff, 0x02, 0xa1, 0x76, 0xa7,
	0x1d, 0x04, 0x00, 0x00,
}

func (m *GenesisState) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *GenesisState) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *GenesisState) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.ActiveNameList) > 0 {
		for iNdEx := len(m.ActiveNameList) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.ActiveNameList[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintGenesis(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x52
		}
	}
	if m.NameRegistrationCount != 0 {
		i = encodeVarintGenesis(dAtA, i, uint64(m.NameRegistrationCount))
		i--
		dAtA[i] = 0x48
	}
	if len(m.NameRegistrationList) > 0 {
		for iNdEx := len(m.NameRegistrationList) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.NameRegistrationList[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintGenesis(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x42
		}
	}
	{
		size := m.TotalBurnedAsteem.Size()
		i -= size
		if _, err := m.TotalBurnedAsteem.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintGenesis(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x3a
	{
		size := m.TotalMintedAsteem.Size()
		i -= size
		if _, err := m.TotalMintedAsteem.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintGenesis(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x32
	if m.WithdrawalCount != 0 {
		i = encodeVarintGenesis(dAtA, i, uint64(m.WithdrawalCount))
		i--
		dAtA[i] = 0x28
	}
	if len(m.WithdrawalList) > 0 {
		for iNdEx := len(m.WithdrawalList) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.WithdrawalList[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintGenesis(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x22
		}
	}
	if m.DepositCount != 0 {
		i = encodeVarintGenesis(dAtA, i, uint64(m.DepositCount))
		i--
		dAtA[i] = 0x18
	}
	if len(m.DepositList) > 0 {
		for iNdEx := len(m.DepositList) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.DepositList[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintGenesis(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x12
		}
	}
	{
		size, err := m.Params.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintGenesis(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func encodeVarintGenesis(dAtA []byte, offset int, v uint64) int {
	offset -= sovGenesis(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *GenesisState) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.Params.Size()
	n += 1 + l + sovGenesis(uint64(l))
	if len(m.DepositList) > 0 {
		for _, e := range m.DepositList {
			l = e.Size()
			n += 1 + l + sovGenesis(uint64(l))
		}
	}
	if m.DepositCount != 0 {
		n += 1 + sovGenesis(uint64(m.DepositCount))
	}
	if len(m.WithdrawalList) > 0 {
		for _, e := range m.WithdrawalList {
			l = e.Size()
			n += 1 + l + sovGenesis(uint64(l))
		}
	}
	if m.WithdrawalCount != 0 {
		n += 1 + sovGenesis(uint64(m.WithdrawalCount))
	}
	l = m.TotalMintedAsteem.Size()
	n += 1 + l + sovGenesis(uint64(l))
	l = m.TotalBurnedAsteem.Size()
	n += 1 + l + sovGenesis(uint64(l))
	if len(m.NameRegistrationList) > 0 {
		for _, e := range m.NameRegistrationList {
			l = e.Size()
			n += 1 + l + sovGenesis(uint64(l))
		}
	}
	if m.NameRegistrationCount != 0 {
		n += 1 + sovGenesis(uint64(m.NameRegistrationCount))
	}
	if len(m.ActiveNameList) > 0 {
		for _, e := range m.ActiveNameList {
			l = e.Size()
			n += 1 + l + sovGenesis(uint64(l))
		}
	}
	return n
}

func sovGenesis(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozGenesis(x uint64) (n int) {
	return sovGenesis(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *GenesisState) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowGenesis
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: GenesisState: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: GenesisState: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Params", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Params.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field DepositList", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.DepositList = append(m.DepositList, Deposit{})
			if err := m.DepositList[len(m.DepositList)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field DepositCount", wireType)
			}
			m.DepositCount = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.DepositCount |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field WithdrawalList", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.WithdrawalList = append(m.WithdrawalList, Withdrawal{})
			if err := m.WithdrawalList[len(m.WithdrawalList)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 5:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field WithdrawalCount", wireType)
			}
			m.WithdrawalCount = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.WithdrawalCount |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field TotalMintedAsteem", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.TotalMintedAsteem.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 7:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field TotalBurnedAsteem", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.TotalBurnedAsteem.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 8:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field NameRegistrationList", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.NameRegistrationList = append(m.NameRegistrationList, NameRegistration{})
			if err := m.NameRegistrationList[len(m.NameRegistrationList)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 9:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field NameRegistrationCount", wireType)
			}
			m.NameRegistrationCount = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.NameRegistrationCount |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 10:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ActiveNameList", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ActiveNameList = append(m.ActiveNameList, NameRecord{})
			if err := m.ActiveNameList[len(m.ActiveNameList)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipGenesis(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthGenesis
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipGenesis(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowGenesis
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthGenesis
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupGenesis
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthGenesis
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthGenesis        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowGenesis          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupGenesis = fmt.Errorf("proto: unexpected end of group")
)
