// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: steemvm/steembridge/v1/tx.proto

package types

import (
	context "context"
	cosmossdk_io_math "cosmossdk.io/math"
	fmt "fmt"
	_ "github.com/cosmos/cosmos-proto"
	_ "github.com/cosmos/cosmos-sdk/types/msgservice"
	_ "github.com/cosmos/cosmos-sdk/types/tx/amino"
	_ "github.com/cosmos/gogoproto/gogoproto"
	grpc1 "github.com/cosmos/gogoproto/grpc"
	proto "github.com/cosmos/gogoproto/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// MsgUpdateParams is the Msg/UpdateParams request type.
type MsgUpdateParams struct {
	// authority is the address that controls the module (defaults to x/gov unless overwritten).
	Authority string `protobuf:"bytes,1,opt,name=authority,proto3" json:"authority,omitempty"`
	// NOTE: All parameters must be supplied.
	Params Params `protobuf:"bytes,2,opt,name=params,proto3" json:"params"`
}

func (m *MsgUpdateParams) Reset()         { *m = MsgUpdateParams{} }
func (m *MsgUpdateParams) String() string { return proto.CompactTextString(m) }
func (*MsgUpdateParams) ProtoMessage()    {}
func (*MsgUpdateParams) Descriptor() ([]byte, []int) {
	return fileDescriptor_71748d65a225c5c8, []int{0}
}
func (m *MsgUpdateParams) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgUpdateParams) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgUpdateParams.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgUpdateParams) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgUpdateParams.Merge(m, src)
}
func (m *MsgUpdateParams) XXX_Size() int {
	return m.Size()
}
func (m *MsgUpdateParams) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgUpdateParams.DiscardUnknown(m)
}

var xxx_messageInfo_MsgUpdateParams proto.InternalMessageInfo

func (m *MsgUpdateParams) GetAuthority() string {
	if m != nil {
		return m.Authority
	}
	return ""
}

func (m *MsgUpdateParams) GetParams() Params {
	if m != nil {
		return m.Params
	}
	return Params{}
}

// MsgUpdateParamsResponse defines the response structure for executing a
// MsgUpdateParams message.
type MsgUpdateParamsResponse struct {
}

func (m *MsgUpdateParamsResponse) Reset()         { *m = MsgUpdateParamsResponse{} }
func (m *MsgUpdateParamsResponse) String() string { return proto.CompactTextString(m) }
func (*MsgUpdateParamsResponse) ProtoMessage()    {}
func (*MsgUpdateParamsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_71748d65a225c5c8, []int{1}
}
func (m *MsgUpdateParamsResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgUpdateParamsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgUpdateParamsResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgUpdateParamsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgUpdateParamsResponse.Merge(m, src)
}
func (m *MsgUpdateParamsResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgUpdateParamsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgUpdateParamsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgUpdateParamsResponse proto.InternalMessageInfo

// MsgAttestDeposit is a bonded validator's attestation of a Steem gateway deposit.
type MsgAttestDeposit struct {
	Validator        string `protobuf:"bytes,1,opt,name=validator,proto3" json:"validator,omitempty"`
	Txid             string `protobuf:"bytes,2,opt,name=txid,proto3" json:"txid,omitempty"`
	OpIndex          uint32 `protobuf:"varint,3,opt,name=op_index,json=opIndex,proto3" json:"op_index,omitempty"`
	SteemBlock       uint64 `protobuf:"varint,4,opt,name=steem_block,json=steemBlock,proto3" json:"steem_block,omitempty"`
	SteemTimestamp   string `protobuf:"bytes,5,opt,name=steem_timestamp,json=steemTimestamp,proto3" json:"steem_timestamp,omitempty"`
	SteemSender      string `protobuf:"bytes,6,opt,name=steem_sender,json=steemSender,proto3" json:"steem_sender,omitempty"`
	GatewayAccount   string `protobuf:"bytes,7,opt,name=gateway_account,json=gatewayAccount,proto3" json:"gateway_account,omitempty"`
	AmountMillisteem uint64 `protobuf:"varint,8,opt,name=amount_millisteem,json=amountMillisteem,proto3" json:"amount_millisteem,omitempty"`
	Memo             string `protobuf:"bytes,9,opt,name=memo,proto3" json:"memo,omitempty"`
	// asset is which native Steem asset was deposited (STEEM or SBD).
	Asset BridgeAsset `protobuf:"varint,10,opt,name=asset,proto3,enum=steemvm.steembridge.v1.BridgeAsset" json:"asset,omitempty"`
}

func (m *MsgAttestDeposit) Reset()         { *m = MsgAttestDeposit{} }
func (m *MsgAttestDeposit) String() string { return proto.CompactTextString(m) }
func (*MsgAttestDeposit) ProtoMessage()    {}
func (*MsgAttestDeposit) Descriptor() ([]byte, []int) {
	return fileDescriptor_71748d65a225c5c8, []int{2}
}
func (m *MsgAttestDeposit) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgAttestDeposit) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgAttestDeposit.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgAttestDeposit) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgAttestDeposit.Merge(m, src)
}
func (m *MsgAttestDeposit) XXX_Size() int {
	return m.Size()
}
func (m *MsgAttestDeposit) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgAttestDeposit.DiscardUnknown(m)
}

var xxx_messageInfo_MsgAttestDeposit proto.InternalMessageInfo

func (m *MsgAttestDeposit) GetValidator() string {
	if m != nil {
		return m.Validator
	}
	return ""
}

func (m *MsgAttestDeposit) GetTxid() string {
	if m != nil {
		return m.Txid
	}
	return ""
}

func (m *MsgAttestDeposit) GetOpIndex() uint32 {
	if m != nil {
		return m.OpIndex
	}
	return 0
}

func (m *MsgAttestDeposit) GetSteemBlock() uint64 {
	if m != nil {
		return m.SteemBlock
	}
	return 0
}

func (m *MsgAttestDeposit) GetSteemTimestamp() string {
	if m != nil {
		return m.SteemTimestamp
	}
	return ""
}

func (m *MsgAttestDeposit) GetSteemSender() string {
	if m != nil {
		return m.SteemSender
	}
	return ""
}

func (m *MsgAttestDeposit) GetGatewayAccount() string {
	if m != nil {
		return m.GatewayAccount
	}
	return ""
}

func (m *MsgAttestDeposit) GetAmountMillisteem() uint64 {
	if m != nil {
		return m.AmountMillisteem
	}
	return 0
}

func (m *MsgAttestDeposit) GetMemo() string {
	if m != nil {
		return m.Memo
	}
	return ""
}

func (m *MsgAttestDeposit) GetAsset() BridgeAsset {
	if m != nil {
		return m.Asset
	}
	return BridgeAsset_BRIDGE_ASSET_STEEM
}

// MsgAttestDepositResponse defines the MsgAttestDeposit response.
type MsgAttestDepositResponse struct {
}

func (m *MsgAttestDepositResponse) Reset()         { *m = MsgAttestDepositResponse{} }
func (m *MsgAttestDepositResponse) String() string { return proto.CompactTextString(m) }
func (*MsgAttestDepositResponse) ProtoMessage()    {}
func (*MsgAttestDepositResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_71748d65a225c5c8, []int{3}
}
func (m *MsgAttestDepositResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgAttestDepositResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgAttestDepositResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgAttestDepositResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgAttestDepositResponse.Merge(m, src)
}
func (m *MsgAttestDepositResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgAttestDepositResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgAttestDepositResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgAttestDepositResponse proto.InternalMessageInfo

// MsgBridgeOut defines the MsgBridgeOut message.
type MsgBridgeOut struct {
	Sender                  string                `protobuf:"bytes,1,opt,name=sender,proto3" json:"sender,omitempty"`
	DestinationSteemAccount string                `protobuf:"bytes,2,opt,name=destination_steem_account,json=destinationSteemAccount,proto3" json:"destination_steem_account,omitempty"`
	AmountAsteem            cosmossdk_io_math.Int `protobuf:"bytes,3,opt,name=amount_asteem,json=amountAsteem,proto3,customtype=cosmossdk.io/math.Int" json:"amount_asteem"`
	Memo                    string                `protobuf:"bytes,4,opt,name=memo,proto3" json:"memo,omitempty"`
	// asset is which native coin to burn (STEEM=asteem, SBD=asbd). Default STEEM.
	Asset BridgeAsset `protobuf:"varint,5,opt,name=asset,proto3,enum=steemvm.steembridge.v1.BridgeAsset" json:"asset,omitempty"`
}

func (m *MsgBridgeOut) Reset()         { *m = MsgBridgeOut{} }
func (m *MsgBridgeOut) String() string { return proto.CompactTextString(m) }
func (*MsgBridgeOut) ProtoMessage()    {}
func (*MsgBridgeOut) Descriptor() ([]byte, []int) {
	return fileDescriptor_71748d65a225c5c8, []int{4}
}
func (m *MsgBridgeOut) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgBridgeOut) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgBridgeOut.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgBridgeOut) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgBridgeOut.Merge(m, src)
}
func (m *MsgBridgeOut) XXX_Size() int {
	return m.Size()
}
func (m *MsgBridgeOut) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgBridgeOut.DiscardUnknown(m)
}

var xxx_messageInfo_MsgBridgeOut proto.InternalMessageInfo

func (m *MsgBridgeOut) GetSender() string {
	if m != nil {
		return m.Sender
	}
	return ""
}

func (m *MsgBridgeOut) GetDestinationSteemAccount() string {
	if m != nil {
		return m.DestinationSteemAccount
	}
	return ""
}

func (m *MsgBridgeOut) GetMemo() string {
	if m != nil {
		return m.Memo
	}
	return ""
}

func (m *MsgBridgeOut) GetAsset() BridgeAsset {
	if m != nil {
		return m.Asset
	}
	return BridgeAsset_BRIDGE_ASSET_STEEM
}

// MsgBridgeOutResponse defines the MsgBridgeOutResponse message.
type MsgBridgeOutResponse struct {
}

func (m *MsgBridgeOutResponse) Reset()         { *m = MsgBridgeOutResponse{} }
func (m *MsgBridgeOutResponse) String() string { return proto.CompactTextString(m) }
func (*MsgBridgeOutResponse) ProtoMessage()    {}
func (*MsgBridgeOutResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_71748d65a225c5c8, []int{5}
}
func (m *MsgBridgeOutResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgBridgeOutResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgBridgeOutResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgBridgeOutResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgBridgeOutResponse.Merge(m, src)
}
func (m *MsgBridgeOutResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgBridgeOutResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgBridgeOutResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgBridgeOutResponse proto.InternalMessageInfo

// MsgAttestWithdrawalPayout is a bonded validator's attestation that the gateway
// paid a bridge-out to the user on Steem (memo "svm-withdrawal <id>").
type MsgAttestWithdrawalPayout struct {
	Validator      string `protobuf:"bytes,1,opt,name=validator,proto3" json:"validator,omitempty"`
	WithdrawalId   uint64 `protobuf:"varint,2,opt,name=withdrawal_id,json=withdrawalId,proto3" json:"withdrawal_id,omitempty"`
	SteemTxid      string `protobuf:"bytes,3,opt,name=steem_txid,json=steemTxid,proto3" json:"steem_txid,omitempty"`
	OpIndex        uint32 `protobuf:"varint,4,opt,name=op_index,json=opIndex,proto3" json:"op_index,omitempty"`
	SteemBlock     uint64 `protobuf:"varint,5,opt,name=steem_block,json=steemBlock,proto3" json:"steem_block,omitempty"`
	SteemTimestamp string `protobuf:"bytes,6,opt,name=steem_timestamp,json=steemTimestamp,proto3" json:"steem_timestamp,omitempty"`
	// amount_millisteem is the amount the validator observed actually paid out
	// on Steem (not the expected amount from the Withdrawal record) — the
	// keeper cross-checks this against the record so a wrong-asset/wrong-amount
	// manual relay can't be confirmed as a valid payout.
	AmountMillisteem uint64 `protobuf:"varint,7,opt,name=amount_millisteem,json=amountMillisteem,proto3" json:"amount_millisteem,omitempty"`
	// asset is the asset the validator observed actually paid out on Steem.
	Asset BridgeAsset `protobuf:"varint,8,opt,name=asset,proto3,enum=steemvm.steembridge.v1.BridgeAsset" json:"asset,omitempty"`
}

func (m *MsgAttestWithdrawalPayout) Reset()         { *m = MsgAttestWithdrawalPayout{} }
func (m *MsgAttestWithdrawalPayout) String() string { return proto.CompactTextString(m) }
func (*MsgAttestWithdrawalPayout) ProtoMessage()    {}
func (*MsgAttestWithdrawalPayout) Descriptor() ([]byte, []int) {
	return fileDescriptor_71748d65a225c5c8, []int{6}
}
func (m *MsgAttestWithdrawalPayout) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgAttestWithdrawalPayout) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgAttestWithdrawalPayout.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgAttestWithdrawalPayout) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgAttestWithdrawalPayout.Merge(m, src)
}
func (m *MsgAttestWithdrawalPayout) XXX_Size() int {
	return m.Size()
}
func (m *MsgAttestWithdrawalPayout) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgAttestWithdrawalPayout.DiscardUnknown(m)
}

var xxx_messageInfo_MsgAttestWithdrawalPayout proto.InternalMessageInfo

func (m *MsgAttestWithdrawalPayout) GetValidator() string {
	if m != nil {
		return m.Validator
	}
	return ""
}

func (m *MsgAttestWithdrawalPayout) GetWithdrawalId() uint64 {
	if m != nil {
		return m.WithdrawalId
	}
	return 0
}

func (m *MsgAttestWithdrawalPayout) GetSteemTxid() string {
	if m != nil {
		return m.SteemTxid
	}
	return ""
}

func (m *MsgAttestWithdrawalPayout) GetOpIndex() uint32 {
	if m != nil {
		return m.OpIndex
	}
	return 0
}

func (m *MsgAttestWithdrawalPayout) GetSteemBlock() uint64 {
	if m != nil {
		return m.SteemBlock
	}
	return 0
}

func (m *MsgAttestWithdrawalPayout) GetSteemTimestamp() string {
	if m != nil {
		return m.SteemTimestamp
	}
	return ""
}

func (m *MsgAttestWithdrawalPayout) GetAmountMillisteem() uint64 {
	if m != nil {
		return m.AmountMillisteem
	}
	return 0
}

func (m *MsgAttestWithdrawalPayout) GetAsset() BridgeAsset {
	if m != nil {
		return m.Asset
	}
	return BridgeAsset_BRIDGE_ASSET_STEEM
}

// MsgAttestWithdrawalPayoutResponse defines the MsgAttestWithdrawalPayout response.
type MsgAttestWithdrawalPayoutResponse struct {
}

func (m *MsgAttestWithdrawalPayoutResponse) Reset()         { *m = MsgAttestWithdrawalPayoutResponse{} }
func (m *MsgAttestWithdrawalPayoutResponse) String() string { return proto.CompactTextString(m) }
func (*MsgAttestWithdrawalPayoutResponse) ProtoMessage()    {}
func (*MsgAttestWithdrawalPayoutResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_71748d65a225c5c8, []int{7}
}
func (m *MsgAttestWithdrawalPayoutResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgAttestWithdrawalPayoutResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgAttestWithdrawalPayoutResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgAttestWithdrawalPayoutResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgAttestWithdrawalPayoutResponse.Merge(m, src)
}
func (m *MsgAttestWithdrawalPayoutResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgAttestWithdrawalPayoutResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgAttestWithdrawalPayoutResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgAttestWithdrawalPayoutResponse proto.InternalMessageInfo

// MsgSubmitNameRegistration is a bonded validator's attestation that a Steem
// account sent a qualifying transfer to the gateway requesting a name link.
type MsgSubmitNameRegistration struct {
	Validator      string `protobuf:"bytes,1,opt,name=validator,proto3" json:"validator,omitempty"`
	Txid           string `protobuf:"bytes,2,opt,name=txid,proto3" json:"txid,omitempty"`
	OpIndex        uint32 `protobuf:"varint,3,opt,name=op_index,json=opIndex,proto3" json:"op_index,omitempty"`
	SteemBlock     uint64 `protobuf:"varint,4,opt,name=steem_block,json=steemBlock,proto3" json:"steem_block,omitempty"`
	SteemTimestamp string `protobuf:"bytes,5,opt,name=steem_timestamp,json=steemTimestamp,proto3" json:"steem_timestamp,omitempty"`
	// steem_account is the Steem-side sender — the name being linked.
	SteemAccount     string `protobuf:"bytes,6,opt,name=steem_account,json=steemAccount,proto3" json:"steem_account,omitempty"`
	GatewayAccount   string `protobuf:"bytes,7,opt,name=gateway_account,json=gatewayAccount,proto3" json:"gateway_account,omitempty"`
	AmountMillisteem uint64 `protobuf:"varint,8,opt,name=amount_millisteem,json=amountMillisteem,proto3" json:"amount_millisteem,omitempty"`
	Memo             string `protobuf:"bytes,9,opt,name=memo,proto3" json:"memo,omitempty"`
}

func (m *MsgSubmitNameRegistration) Reset()         { *m = MsgSubmitNameRegistration{} }
func (m *MsgSubmitNameRegistration) String() string { return proto.CompactTextString(m) }
func (*MsgSubmitNameRegistration) ProtoMessage()    {}
func (*MsgSubmitNameRegistration) Descriptor() ([]byte, []int) {
	return fileDescriptor_71748d65a225c5c8, []int{8}
}
func (m *MsgSubmitNameRegistration) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgSubmitNameRegistration) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgSubmitNameRegistration.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgSubmitNameRegistration) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgSubmitNameRegistration.Merge(m, src)
}
func (m *MsgSubmitNameRegistration) XXX_Size() int {
	return m.Size()
}
func (m *MsgSubmitNameRegistration) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgSubmitNameRegistration.DiscardUnknown(m)
}

var xxx_messageInfo_MsgSubmitNameRegistration proto.InternalMessageInfo

func (m *MsgSubmitNameRegistration) GetValidator() string {
	if m != nil {
		return m.Validator
	}
	return ""
}

func (m *MsgSubmitNameRegistration) GetTxid() string {
	if m != nil {
		return m.Txid
	}
	return ""
}

func (m *MsgSubmitNameRegistration) GetOpIndex() uint32 {
	if m != nil {
		return m.OpIndex
	}
	return 0
}

func (m *MsgSubmitNameRegistration) GetSteemBlock() uint64 {
	if m != nil {
		return m.SteemBlock
	}
	return 0
}

func (m *MsgSubmitNameRegistration) GetSteemTimestamp() string {
	if m != nil {
		return m.SteemTimestamp
	}
	return ""
}

func (m *MsgSubmitNameRegistration) GetSteemAccount() string {
	if m != nil {
		return m.SteemAccount
	}
	return ""
}

func (m *MsgSubmitNameRegistration) GetGatewayAccount() string {
	if m != nil {
		return m.GatewayAccount
	}
	return ""
}

func (m *MsgSubmitNameRegistration) GetAmountMillisteem() uint64 {
	if m != nil {
		return m.AmountMillisteem
	}
	return 0
}

func (m *MsgSubmitNameRegistration) GetMemo() string {
	if m != nil {
		return m.Memo
	}
	return ""
}

// MsgSubmitNameRegistrationResponse defines the MsgSubmitNameRegistrationResponse message.
type MsgSubmitNameRegistrationResponse struct {
}

func (m *MsgSubmitNameRegistrationResponse) Reset()         { *m = MsgSubmitNameRegistrationResponse{} }
func (m *MsgSubmitNameRegistrationResponse) String() string { return proto.CompactTextString(m) }
func (*MsgSubmitNameRegistrationResponse) ProtoMessage()    {}
func (*MsgSubmitNameRegistrationResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_71748d65a225c5c8, []int{9}
}
func (m *MsgSubmitNameRegistrationResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgSubmitNameRegistrationResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgSubmitNameRegistrationResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgSubmitNameRegistrationResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgSubmitNameRegistrationResponse.Merge(m, src)
}
func (m *MsgSubmitNameRegistrationResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgSubmitNameRegistrationResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgSubmitNameRegistrationResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgSubmitNameRegistrationResponse proto.InternalMessageInfo

// MsgConfirmName is signed by the memo-derived destination address to accept
// a name registration that has reached the validator confirmation threshold.
type MsgConfirmName struct {
	Confirmer      string `protobuf:"bytes,1,opt,name=confirmer,proto3" json:"confirmer,omitempty"`
	RegistrationId uint64 `protobuf:"varint,2,opt,name=registration_id,json=registrationId,proto3" json:"registration_id,omitempty"`
}

func (m *MsgConfirmName) Reset()         { *m = MsgConfirmName{} }
func (m *MsgConfirmName) String() string { return proto.CompactTextString(m) }
func (*MsgConfirmName) ProtoMessage()    {}
func (*MsgConfirmName) Descriptor() ([]byte, []int) {
	return fileDescriptor_71748d65a225c5c8, []int{10}
}
func (m *MsgConfirmName) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgConfirmName) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgConfirmName.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgConfirmName) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgConfirmName.Merge(m, src)
}
func (m *MsgConfirmName) XXX_Size() int {
	return m.Size()
}
func (m *MsgConfirmName) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgConfirmName.DiscardUnknown(m)
}

var xxx_messageInfo_MsgConfirmName proto.InternalMessageInfo

func (m *MsgConfirmName) GetConfirmer() string {
	if m != nil {
		return m.Confirmer
	}
	return ""
}

func (m *MsgConfirmName) GetRegistrationId() uint64 {
	if m != nil {
		return m.RegistrationId
	}
	return 0
}

// MsgConfirmNameResponse defines the MsgConfirmNameResponse message.
type MsgConfirmNameResponse struct {
}

func (m *MsgConfirmNameResponse) Reset()         { *m = MsgConfirmNameResponse{} }
func (m *MsgConfirmNameResponse) String() string { return proto.CompactTextString(m) }
func (*MsgConfirmNameResponse) ProtoMessage()    {}
func (*MsgConfirmNameResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_71748d65a225c5c8, []int{11}
}
func (m *MsgConfirmNameResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgConfirmNameResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgConfirmNameResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgConfirmNameResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgConfirmNameResponse.Merge(m, src)
}
func (m *MsgConfirmNameResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgConfirmNameResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgConfirmNameResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgConfirmNameResponse proto.InternalMessageInfo

func init() {
	proto.RegisterType((*MsgUpdateParams)(nil), "steemvm.steembridge.v1.MsgUpdateParams")
	proto.RegisterType((*MsgUpdateParamsResponse)(nil), "steemvm.steembridge.v1.MsgUpdateParamsResponse")
	proto.RegisterType((*MsgAttestDeposit)(nil), "steemvm.steembridge.v1.MsgAttestDeposit")
	proto.RegisterType((*MsgAttestDepositResponse)(nil), "steemvm.steembridge.v1.MsgAttestDepositResponse")
	proto.RegisterType((*MsgBridgeOut)(nil), "steemvm.steembridge.v1.MsgBridgeOut")
	proto.RegisterType((*MsgBridgeOutResponse)(nil), "steemvm.steembridge.v1.MsgBridgeOutResponse")
	proto.RegisterType((*MsgAttestWithdrawalPayout)(nil), "steemvm.steembridge.v1.MsgAttestWithdrawalPayout")
	proto.RegisterType((*MsgAttestWithdrawalPayoutResponse)(nil), "steemvm.steembridge.v1.MsgAttestWithdrawalPayoutResponse")
	proto.RegisterType((*MsgSubmitNameRegistration)(nil), "steemvm.steembridge.v1.MsgSubmitNameRegistration")
	proto.RegisterType((*MsgSubmitNameRegistrationResponse)(nil), "steemvm.steembridge.v1.MsgSubmitNameRegistrationResponse")
	proto.RegisterType((*MsgConfirmName)(nil), "steemvm.steembridge.v1.MsgConfirmName")
	proto.RegisterType((*MsgConfirmNameResponse)(nil), "steemvm.steembridge.v1.MsgConfirmNameResponse")
}

func init() { proto.RegisterFile("steemvm/steembridge/v1/tx.proto", fileDescriptor_71748d65a225c5c8) }

var fileDescriptor_71748d65a225c5c8 = []byte{
	// 949 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xd4, 0x56, 0xbd, 0x6f, 0x23, 0x45,
	0x14, 0xcf, 0x26, 0xb6, 0x13, 0xbf, 0xd8, 0xbe, 0xbb, 0x55, 0x48, 0xd6, 0x2b, 0xc5, 0xf1, 0xd9,
	0xc0, 0x59, 0x01, 0xbc, 0x97, 0x20, 0x01, 0x97, 0xce, 0x86, 0x26, 0x85, 0xe1, 0xb4, 0x01, 0x21,
	0xd1, 0x58, 0x13, 0xef, 0xb0, 0x19, 0xc5, 0xbb, 0xb3, 0xda, 0x19, 0xe7, 0xa3, 0x03, 0x0a, 0x0a,
	0x2a, 0x7a, 0xf8, 0x03, 0x28, 0x53, 0xd0, 0xd2, 0xa2, 0x2b, 0x4f, 0x54, 0x88, 0xe2, 0x84, 0x92,
	0x22, 0x05, 0x2d, 0x7f, 0x00, 0x9a, 0x0f, 0xaf, 0x3f, 0xe4, 0x75, 0x7c, 0x20, 0x21, 0x5d, 0x63,
	0xcf, 0xbc, 0xf9, 0xbd, 0xaf, 0xdf, 0x7b, 0x6f, 0x76, 0x60, 0x87, 0x71, 0x8c, 0x83, 0xb3, 0xc0,
	0x91, 0xff, 0xc7, 0x31, 0xf1, 0x7c, 0xec, 0x9c, 0xed, 0x39, 0xfc, 0xa2, 0x19, 0xc5, 0x94, 0x53,
	0x73, 0x53, 0x03, 0x9a, 0x63, 0x80, 0xe6, 0xd9, 0x9e, 0xfd, 0x00, 0x05, 0x24, 0xa4, 0x8e, 0xfc,
	0x55, 0x50, 0x7b, 0xab, 0x47, 0x59, 0x40, 0x99, 0x13, 0x30, 0x5f, 0x98, 0x08, 0x98, 0xaf, 0x0f,
	0xca, 0xea, 0xa0, 0x2b, 0x77, 0x8e, 0xda, 0xe8, 0xa3, 0x0d, 0x9f, 0xfa, 0x54, 0xc9, 0xc5, 0x4a,
	0x4b, 0x6b, 0x29, 0x51, 0x21, 0xc6, 0x30, 0xd7, 0x98, 0x7a, 0x0a, 0x26, 0x42, 0x31, 0x0a, 0xb4,
	0xf9, 0xda, 0xaf, 0x06, 0xdc, 0xeb, 0x30, 0xff, 0xb3, 0xc8, 0x43, 0x1c, 0x3f, 0x95, 0x27, 0xe6,
	0x7b, 0x90, 0x47, 0x03, 0x7e, 0x42, 0x63, 0xc2, 0x2f, 0x2d, 0xa3, 0x6a, 0x34, 0xf2, 0x6d, 0xeb,
	0xb7, 0x9f, 0xdf, 0xd9, 0xd0, 0x71, 0xb5, 0x3c, 0x2f, 0xc6, 0x8c, 0x1d, 0xf1, 0x98, 0x84, 0xbe,
	0x3b, 0x82, 0x9a, 0x2d, 0xc8, 0x29, 0xdb, 0xd6, 0x72, 0xd5, 0x68, 0xac, 0xef, 0x57, 0x9a, 0xb3,
	0xa9, 0x69, 0x2a, 0x3f, 0xed, 0xfc, 0xb3, 0x17, 0x3b, 0x4b, 0x3f, 0xdd, 0x5e, 0xed, 0x1a, 0xae,
	0x56, 0x3c, 0xf8, 0xe0, 0x9b, 0xdb, 0xab, 0xdd, 0x91, 0xc9, 0xef, 0x6e, 0xaf, 0x76, 0xdf, 0x18,
	0xa6, 0x71, 0x31, 0x91, 0xc8, 0x54, 0xd0, 0xb5, 0x32, 0x6c, 0x4d, 0x89, 0x5c, 0xcc, 0x22, 0x1a,
	0x32, 0x5c, 0xfb, 0x61, 0x05, 0xee, 0x77, 0x98, 0xdf, 0xe2, 0x1c, 0x33, 0xfe, 0x11, 0x8e, 0x28,
	0x23, 0x5c, 0x24, 0x79, 0x86, 0xfa, 0xc4, 0x43, 0x9c, 0xc6, 0x77, 0x27, 0x99, 0x40, 0x4d, 0x13,
	0x32, 0xfc, 0x82, 0x78, 0x32, 0xc5, 0xbc, 0x2b, 0xd7, 0x66, 0x19, 0xd6, 0x68, 0xd4, 0x25, 0xa1,
	0x87, 0x2f, 0xac, 0x95, 0xaa, 0xd1, 0x28, 0xba, 0xab, 0x34, 0x3a, 0x14, 0x5b, 0x73, 0x07, 0xd6,
	0x65, 0xd4, 0xdd, 0xe3, 0x3e, 0xed, 0x9d, 0x5a, 0x99, 0xaa, 0xd1, 0xc8, 0xb8, 0x20, 0x45, 0x6d,
	0x21, 0x31, 0x1f, 0xc1, 0x3d, 0x05, 0xe0, 0x24, 0xc0, 0x8c, 0xa3, 0x20, 0xb2, 0xb2, 0xd2, 0x74,
	0x49, 0x8a, 0x3f, 0x1d, 0x4a, 0xcd, 0x87, 0x50, 0x50, 0x40, 0x86, 0x43, 0x0f, 0xc7, 0x56, 0x4e,
	0xa2, 0x94, 0xf5, 0x23, 0x29, 0x12, 0xb6, 0x7c, 0xc4, 0xf1, 0x39, 0xba, 0xec, 0xa2, 0x5e, 0x8f,
	0x0e, 0x42, 0x6e, 0xad, 0x2a, 0x5b, 0x5a, 0xdc, 0x52, 0x52, 0xf3, 0x2d, 0x78, 0x80, 0x02, 0xb1,
	0xea, 0x06, 0xa4, 0xdf, 0x27, 0xd2, 0x86, 0xb5, 0x26, 0x63, 0xbb, 0xaf, 0x0e, 0x3a, 0x89, 0x5c,
	0x64, 0x1c, 0xe0, 0x80, 0x5a, 0x79, 0x95, 0xb1, 0x58, 0x9b, 0x4f, 0x20, 0x2b, 0x5b, 0xcd, 0x82,
	0xaa, 0xd1, 0x28, 0xed, 0xd7, 0xd3, 0x2a, 0xdd, 0x96, 0xab, 0x96, 0x80, 0xba, 0x4a, 0xe3, 0xa0,
	0x24, 0x4b, 0x9c, 0x10, 0x5a, 0xb3, 0xc1, 0x9a, 0x2e, 0x4e, 0x52, 0xb9, 0x1f, 0x97, 0xa1, 0xd0,
	0x61, 0xbe, 0xb2, 0xf2, 0xc9, 0x80, 0x9b, 0x8f, 0x21, 0xa7, 0xd3, 0xbf, 0xab, 0x64, 0x1a, 0x67,
	0x1e, 0x40, 0xd9, 0xc3, 0x8c, 0x93, 0x10, 0x71, 0x42, 0xc3, 0xae, 0xa2, 0x70, 0xc8, 0x8e, 0x2a,
	0xe2, 0xd6, 0x18, 0xe0, 0x48, 0x9c, 0x0f, 0x69, 0x6a, 0x43, 0x51, 0xd3, 0x84, 0x14, 0x45, 0x2b,
	0xd2, 0xe9, 0xb6, 0xe8, 0xdb, 0x3f, 0x5e, 0xec, 0xbc, 0xa6, 0x1c, 0x33, 0xef, 0xb4, 0x49, 0xa8,
	0x13, 0x20, 0x7e, 0xd2, 0x3c, 0x0c, 0xb9, 0x5b, 0x50, 0x3a, 0xad, 0x49, 0xf6, 0x32, 0xb3, 0xd8,
	0xcb, 0xbe, 0x34, 0x7b, 0xeb, 0x82, 0x3d, 0x9d, 0x5b, 0x6d, 0x13, 0x36, 0xc6, 0xd9, 0x49, 0x68,
	0xfb, 0x7b, 0x19, 0xca, 0x09, 0xa7, 0x9f, 0x13, 0x7e, 0xe2, 0xc5, 0xe8, 0x1c, 0xf5, 0x9f, 0xa2,
	0x4b, 0x3a, 0xf8, 0xf7, 0x9d, 0x5f, 0x87, 0xe2, 0x79, 0x62, 0xab, 0xab, 0x47, 0x20, 0xe3, 0x16,
	0x46, 0xc2, 0x43, 0xcf, 0xdc, 0x06, 0xd0, 0xed, 0x2c, 0x86, 0x44, 0xf2, 0xe5, 0xe6, 0x55, 0x27,
	0x4f, 0x4f, 0x4a, 0x66, 0xee, 0xa4, 0x64, 0x17, 0x99, 0x94, 0xdc, 0xcc, 0x49, 0x99, 0xd9, 0xdd,
	0xab, 0x29, 0xdd, 0x9d, 0xd4, 0x62, 0xed, 0x3f, 0x77, 0x72, 0x1d, 0x1e, 0xa6, 0xb2, 0x9e, 0xd4,
	0xe6, 0x2f, 0x55, 0x9b, 0xa3, 0xc1, 0x71, 0x40, 0xf8, 0xc7, 0x28, 0xc0, 0x2e, 0xf6, 0x09, 0xe3,
	0xb1, 0xec, 0xbe, 0x57, 0xef, 0x56, 0xaa, 0x43, 0x71, 0x72, 0xa4, 0x54, 0x49, 0xd4, 0x55, 0x35,
	0x9c, 0xa3, 0xff, 0xed, 0x5e, 0x4a, 0x29, 0xc9, 0x6c, 0xb2, 0x93, 0x92, 0x7c, 0x6d, 0x40, 0xa9,
	0xc3, 0xfc, 0x0f, 0x69, 0xf8, 0x25, 0x89, 0x03, 0x01, 0x13, 0x75, 0xe8, 0xa9, 0xed, 0x02, 0x57,
	0xcd, 0x08, 0x2a, 0x32, 0x8d, 0xc7, 0x5c, 0x8c, 0xa6, 0xa4, 0x34, 0x2e, 0x3e, 0xf4, 0x74, 0xa0,
	0x89, 0x62, 0xcd, 0x82, 0xcd, 0xc9, 0x10, 0x86, 0xd1, 0xed, 0xff, 0x92, 0x85, 0x95, 0x0e, 0xf3,
	0xcd, 0x13, 0x28, 0x4c, 0x7c, 0xa5, 0x1f, 0xa5, 0x75, 0xea, 0xd4, 0x67, 0xd0, 0x76, 0x16, 0x04,
	0x0e, 0x3d, 0x9a, 0xa7, 0x50, 0x9c, 0xfc, 0x56, 0x36, 0xe6, 0x58, 0x98, 0x40, 0xda, 0x8f, 0x17,
	0x45, 0x26, 0xce, 0xba, 0x90, 0x1f, 0x5d, 0xef, 0xaf, 0xcf, 0x51, 0x4f, 0x50, 0xf6, 0xdb, 0x8b,
	0xa0, 0x12, 0x07, 0xdf, 0x1a, 0xb0, 0x99, 0x72, 0x13, 0xee, 0xdd, 0x19, 0xed, 0xb4, 0x8a, 0xfd,
	0xe4, 0xa5, 0x55, 0x26, 0x02, 0x49, 0x19, 0xfb, 0x79, 0x81, 0xcc, 0x56, 0x99, 0x1b, 0xc8, 0xfc,
	0x7e, 0x37, 0x31, 0xac, 0x8f, 0xf7, 0xfa, 0x9b, 0x73, 0x2c, 0x8d, 0xe1, 0xec, 0xe6, 0x62, 0xb8,
	0xa1, 0x1b, 0x3b, 0xfb, 0x95, 0x78, 0xda, 0xb5, 0xdf, 0x7f, 0x76, 0x5d, 0x31, 0x9e, 0x5f, 0x57,
	0x8c, 0x3f, 0xaf, 0x2b, 0xc6, 0xf7, 0x37, 0x95, 0xa5, 0xe7, 0x37, 0x95, 0xa5, 0xdf, 0x6f, 0x2a,
	0x4b, 0x5f, 0x6c, 0x8f, 0x5e, 0x76, 0x34, 0x46, 0xbd, 0x3e, 0x76, 0xf4, 0xdb, 0x8e, 0x5f, 0x46,
	0x98, 0x1d, 0xe7, 0xe4, 0x0b, 0xf5, 0xdd, 0x7f, 0x02, 0x00, 0x00, 0xff, 0xff, 0x91, 0x37, 0x33,
	0x08, 0x82, 0x0b, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// MsgClient is the client API for Msg service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type MsgClient interface {
	// UpdateParams defines a (governance) operation for updating the module
	// parameters. The authority defaults to the x/gov module account.
	UpdateParams(ctx context.Context, in *MsgUpdateParams, opts ...grpc.CallOption) (*MsgUpdateParamsResponse, error)
	// AttestDeposit is a bonded validator's attestation of a Steem gateway deposit
	// (STEEM or SBD). At 2/3 bonded power the deposit finalizes and mints.
	AttestDeposit(ctx context.Context, in *MsgAttestDeposit, opts ...grpc.CallOption) (*MsgAttestDepositResponse, error)
	// BridgeOut defines the BridgeOut RPC.
	BridgeOut(ctx context.Context, in *MsgBridgeOut, opts ...grpc.CallOption) (*MsgBridgeOutResponse, error)
	// AttestWithdrawalPayout is a bonded validator's attestation that the gateway
	// paid a bridge-out on Steem. At 2/3 the withdrawal is marked PROCESSED.
	AttestWithdrawalPayout(ctx context.Context, in *MsgAttestWithdrawalPayout, opts ...grpc.CallOption) (*MsgAttestWithdrawalPayoutResponse, error)
	// SubmitNameRegistration defines the SubmitNameRegistration RPC.
	SubmitNameRegistration(ctx context.Context, in *MsgSubmitNameRegistration, opts ...grpc.CallOption) (*MsgSubmitNameRegistrationResponse, error)
	// ConfirmName defines the ConfirmName RPC.
	ConfirmName(ctx context.Context, in *MsgConfirmName, opts ...grpc.CallOption) (*MsgConfirmNameResponse, error)
}

type msgClient struct {
	cc grpc1.ClientConn
}

func NewMsgClient(cc grpc1.ClientConn) MsgClient {
	return &msgClient{cc}
}

func (c *msgClient) UpdateParams(ctx context.Context, in *MsgUpdateParams, opts ...grpc.CallOption) (*MsgUpdateParamsResponse, error) {
	out := new(MsgUpdateParamsResponse)
	err := c.cc.Invoke(ctx, "/steemvm.steembridge.v1.Msg/UpdateParams", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) AttestDeposit(ctx context.Context, in *MsgAttestDeposit, opts ...grpc.CallOption) (*MsgAttestDepositResponse, error) {
	out := new(MsgAttestDepositResponse)
	err := c.cc.Invoke(ctx, "/steemvm.steembridge.v1.Msg/AttestDeposit", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) BridgeOut(ctx context.Context, in *MsgBridgeOut, opts ...grpc.CallOption) (*MsgBridgeOutResponse, error) {
	out := new(MsgBridgeOutResponse)
	err := c.cc.Invoke(ctx, "/steemvm.steembridge.v1.Msg/BridgeOut", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) AttestWithdrawalPayout(ctx context.Context, in *MsgAttestWithdrawalPayout, opts ...grpc.CallOption) (*MsgAttestWithdrawalPayoutResponse, error) {
	out := new(MsgAttestWithdrawalPayoutResponse)
	err := c.cc.Invoke(ctx, "/steemvm.steembridge.v1.Msg/AttestWithdrawalPayout", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) SubmitNameRegistration(ctx context.Context, in *MsgSubmitNameRegistration, opts ...grpc.CallOption) (*MsgSubmitNameRegistrationResponse, error) {
	out := new(MsgSubmitNameRegistrationResponse)
	err := c.cc.Invoke(ctx, "/steemvm.steembridge.v1.Msg/SubmitNameRegistration", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) ConfirmName(ctx context.Context, in *MsgConfirmName, opts ...grpc.CallOption) (*MsgConfirmNameResponse, error) {
	out := new(MsgConfirmNameResponse)
	err := c.cc.Invoke(ctx, "/steemvm.steembridge.v1.Msg/ConfirmName", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MsgServer is the server API for Msg service.
type MsgServer interface {
	// UpdateParams defines a (governance) operation for updating the module
	// parameters. The authority defaults to the x/gov module account.
	UpdateParams(context.Context, *MsgUpdateParams) (*MsgUpdateParamsResponse, error)
	// AttestDeposit is a bonded validator's attestation of a Steem gateway deposit
	// (STEEM or SBD). At 2/3 bonded power the deposit finalizes and mints.
	AttestDeposit(context.Context, *MsgAttestDeposit) (*MsgAttestDepositResponse, error)
	// BridgeOut defines the BridgeOut RPC.
	BridgeOut(context.Context, *MsgBridgeOut) (*MsgBridgeOutResponse, error)
	// AttestWithdrawalPayout is a bonded validator's attestation that the gateway
	// paid a bridge-out on Steem. At 2/3 the withdrawal is marked PROCESSED.
	AttestWithdrawalPayout(context.Context, *MsgAttestWithdrawalPayout) (*MsgAttestWithdrawalPayoutResponse, error)
	// SubmitNameRegistration defines the SubmitNameRegistration RPC.
	SubmitNameRegistration(context.Context, *MsgSubmitNameRegistration) (*MsgSubmitNameRegistrationResponse, error)
	// ConfirmName defines the ConfirmName RPC.
	ConfirmName(context.Context, *MsgConfirmName) (*MsgConfirmNameResponse, error)
}

// UnimplementedMsgServer can be embedded to have forward compatible implementations.
type UnimplementedMsgServer struct {
}

func (*UnimplementedMsgServer) UpdateParams(ctx context.Context, req *MsgUpdateParams) (*MsgUpdateParamsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateParams not implemented")
}
func (*UnimplementedMsgServer) AttestDeposit(ctx context.Context, req *MsgAttestDeposit) (*MsgAttestDepositResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AttestDeposit not implemented")
}
func (*UnimplementedMsgServer) BridgeOut(ctx context.Context, req *MsgBridgeOut) (*MsgBridgeOutResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method BridgeOut not implemented")
}
func (*UnimplementedMsgServer) AttestWithdrawalPayout(ctx context.Context, req *MsgAttestWithdrawalPayout) (*MsgAttestWithdrawalPayoutResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AttestWithdrawalPayout not implemented")
}
func (*UnimplementedMsgServer) SubmitNameRegistration(ctx context.Context, req *MsgSubmitNameRegistration) (*MsgSubmitNameRegistrationResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SubmitNameRegistration not implemented")
}
func (*UnimplementedMsgServer) ConfirmName(ctx context.Context, req *MsgConfirmName) (*MsgConfirmNameResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ConfirmName not implemented")
}

func RegisterMsgServer(s grpc1.Server, srv MsgServer) {
	s.RegisterService(&_Msg_serviceDesc, srv)
}

func _Msg_UpdateParams_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgUpdateParams)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).UpdateParams(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/steemvm.steembridge.v1.Msg/UpdateParams",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).UpdateParams(ctx, req.(*MsgUpdateParams))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_AttestDeposit_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgAttestDeposit)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).AttestDeposit(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/steemvm.steembridge.v1.Msg/AttestDeposit",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).AttestDeposit(ctx, req.(*MsgAttestDeposit))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_BridgeOut_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgBridgeOut)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).BridgeOut(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/steemvm.steembridge.v1.Msg/BridgeOut",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).BridgeOut(ctx, req.(*MsgBridgeOut))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_AttestWithdrawalPayout_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgAttestWithdrawalPayout)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).AttestWithdrawalPayout(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/steemvm.steembridge.v1.Msg/AttestWithdrawalPayout",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).AttestWithdrawalPayout(ctx, req.(*MsgAttestWithdrawalPayout))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_SubmitNameRegistration_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgSubmitNameRegistration)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).SubmitNameRegistration(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/steemvm.steembridge.v1.Msg/SubmitNameRegistration",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).SubmitNameRegistration(ctx, req.(*MsgSubmitNameRegistration))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_ConfirmName_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgConfirmName)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).ConfirmName(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/steemvm.steembridge.v1.Msg/ConfirmName",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).ConfirmName(ctx, req.(*MsgConfirmName))
	}
	return interceptor(ctx, in, info, handler)
}

var Msg_serviceDesc = _Msg_serviceDesc
var _Msg_serviceDesc = grpc.ServiceDesc{
	ServiceName: "steemvm.steembridge.v1.Msg",
	HandlerType: (*MsgServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "UpdateParams",
			Handler:    _Msg_UpdateParams_Handler,
		},
		{
			MethodName: "AttestDeposit",
			Handler:    _Msg_AttestDeposit_Handler,
		},
		{
			MethodName: "BridgeOut",
			Handler:    _Msg_BridgeOut_Handler,
		},
		{
			MethodName: "AttestWithdrawalPayout",
			Handler:    _Msg_AttestWithdrawalPayout_Handler,
		},
		{
			MethodName: "SubmitNameRegistration",
			Handler:    _Msg_SubmitNameRegistration_Handler,
		},
		{
			MethodName: "ConfirmName",
			Handler:    _Msg_ConfirmName_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "steemvm/steembridge/v1/tx.proto",
}

func (m *MsgUpdateParams) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgUpdateParams) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgUpdateParams) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.Params.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintTx(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x12
	if len(m.Authority) > 0 {
		i -= len(m.Authority)
		copy(dAtA[i:], m.Authority)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Authority)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgUpdateParamsResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgUpdateParamsResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgUpdateParamsResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *MsgAttestDeposit) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgAttestDeposit) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgAttestDeposit) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Asset != 0 {
		i = encodeVarintTx(dAtA, i, uint64(m.Asset))
		i--
		dAtA[i] = 0x50
	}
	if len(m.Memo) > 0 {
		i -= len(m.Memo)
		copy(dAtA[i:], m.Memo)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Memo)))
		i--
		dAtA[i] = 0x4a
	}
	if m.AmountMillisteem != 0 {
		i = encodeVarintTx(dAtA, i, uint64(m.AmountMillisteem))
		i--
		dAtA[i] = 0x40
	}
	if len(m.GatewayAccount) > 0 {
		i -= len(m.GatewayAccount)
		copy(dAtA[i:], m.GatewayAccount)
		i = encodeVarintTx(dAtA, i, uint64(len(m.GatewayAccount)))
		i--
		dAtA[i] = 0x3a
	}
	if len(m.SteemSender) > 0 {
		i -= len(m.SteemSender)
		copy(dAtA[i:], m.SteemSender)
		i = encodeVarintTx(dAtA, i, uint64(len(m.SteemSender)))
		i--
		dAtA[i] = 0x32
	}
	if len(m.SteemTimestamp) > 0 {
		i -= len(m.SteemTimestamp)
		copy(dAtA[i:], m.SteemTimestamp)
		i = encodeVarintTx(dAtA, i, uint64(len(m.SteemTimestamp)))
		i--
		dAtA[i] = 0x2a
	}
	if m.SteemBlock != 0 {
		i = encodeVarintTx(dAtA, i, uint64(m.SteemBlock))
		i--
		dAtA[i] = 0x20
	}
	if m.OpIndex != 0 {
		i = encodeVarintTx(dAtA, i, uint64(m.OpIndex))
		i--
		dAtA[i] = 0x18
	}
	if len(m.Txid) > 0 {
		i -= len(m.Txid)
		copy(dAtA[i:], m.Txid)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Txid)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Validator) > 0 {
		i -= len(m.Validator)
		copy(dAtA[i:], m.Validator)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Validator)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgAttestDepositResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgAttestDepositResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgAttestDepositResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *MsgBridgeOut) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgBridgeOut) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgBridgeOut) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Asset != 0 {
		i = encodeVarintTx(dAtA, i, uint64(m.Asset))
		i--
		dAtA[i] = 0x28
	}
	if len(m.Memo) > 0 {
		i -= len(m.Memo)
		copy(dAtA[i:], m.Memo)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Memo)))
		i--
		dAtA[i] = 0x22
	}
	{
		size := m.AmountAsteem.Size()
		i -= size
		if _, err := m.AmountAsteem.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintTx(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x1a
	if len(m.DestinationSteemAccount) > 0 {
		i -= len(m.DestinationSteemAccount)
		copy(dAtA[i:], m.DestinationSteemAccount)
		i = encodeVarintTx(dAtA, i, uint64(len(m.DestinationSteemAccount)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Sender) > 0 {
		i -= len(m.Sender)
		copy(dAtA[i:], m.Sender)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Sender)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgBridgeOutResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgBridgeOutResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgBridgeOutResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *MsgAttestWithdrawalPayout) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgAttestWithdrawalPayout) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgAttestWithdrawalPayout) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Asset != 0 {
		i = encodeVarintTx(dAtA, i, uint64(m.Asset))
		i--
		dAtA[i] = 0x40
	}
	if m.AmountMillisteem != 0 {
		i = encodeVarintTx(dAtA, i, uint64(m.AmountMillisteem))
		i--
		dAtA[i] = 0x38
	}
	if len(m.SteemTimestamp) > 0 {
		i -= len(m.SteemTimestamp)
		copy(dAtA[i:], m.SteemTimestamp)
		i = encodeVarintTx(dAtA, i, uint64(len(m.SteemTimestamp)))
		i--
		dAtA[i] = 0x32
	}
	if m.SteemBlock != 0 {
		i = encodeVarintTx(dAtA, i, uint64(m.SteemBlock))
		i--
		dAtA[i] = 0x28
	}
	if m.OpIndex != 0 {
		i = encodeVarintTx(dAtA, i, uint64(m.OpIndex))
		i--
		dAtA[i] = 0x20
	}
	if len(m.SteemTxid) > 0 {
		i -= len(m.SteemTxid)
		copy(dAtA[i:], m.SteemTxid)
		i = encodeVarintTx(dAtA, i, uint64(len(m.SteemTxid)))
		i--
		dAtA[i] = 0x1a
	}
	if m.WithdrawalId != 0 {
		i = encodeVarintTx(dAtA, i, uint64(m.WithdrawalId))
		i--
		dAtA[i] = 0x10
	}
	if len(m.Validator) > 0 {
		i -= len(m.Validator)
		copy(dAtA[i:], m.Validator)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Validator)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgAttestWithdrawalPayoutResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgAttestWithdrawalPayoutResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgAttestWithdrawalPayoutResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *MsgSubmitNameRegistration) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgSubmitNameRegistration) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgSubmitNameRegistration) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Memo) > 0 {
		i -= len(m.Memo)
		copy(dAtA[i:], m.Memo)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Memo)))
		i--
		dAtA[i] = 0x4a
	}
	if m.AmountMillisteem != 0 {
		i = encodeVarintTx(dAtA, i, uint64(m.AmountMillisteem))
		i--
		dAtA[i] = 0x40
	}
	if len(m.GatewayAccount) > 0 {
		i -= len(m.GatewayAccount)
		copy(dAtA[i:], m.GatewayAccount)
		i = encodeVarintTx(dAtA, i, uint64(len(m.GatewayAccount)))
		i--
		dAtA[i] = 0x3a
	}
	if len(m.SteemAccount) > 0 {
		i -= len(m.SteemAccount)
		copy(dAtA[i:], m.SteemAccount)
		i = encodeVarintTx(dAtA, i, uint64(len(m.SteemAccount)))
		i--
		dAtA[i] = 0x32
	}
	if len(m.SteemTimestamp) > 0 {
		i -= len(m.SteemTimestamp)
		copy(dAtA[i:], m.SteemTimestamp)
		i = encodeVarintTx(dAtA, i, uint64(len(m.SteemTimestamp)))
		i--
		dAtA[i] = 0x2a
	}
	if m.SteemBlock != 0 {
		i = encodeVarintTx(dAtA, i, uint64(m.SteemBlock))
		i--
		dAtA[i] = 0x20
	}
	if m.OpIndex != 0 {
		i = encodeVarintTx(dAtA, i, uint64(m.OpIndex))
		i--
		dAtA[i] = 0x18
	}
	if len(m.Txid) > 0 {
		i -= len(m.Txid)
		copy(dAtA[i:], m.Txid)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Txid)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Validator) > 0 {
		i -= len(m.Validator)
		copy(dAtA[i:], m.Validator)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Validator)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgSubmitNameRegistrationResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgSubmitNameRegistrationResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgSubmitNameRegistrationResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *MsgConfirmName) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgConfirmName) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgConfirmName) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.RegistrationId != 0 {
		i = encodeVarintTx(dAtA, i, uint64(m.RegistrationId))
		i--
		dAtA[i] = 0x10
	}
	if len(m.Confirmer) > 0 {
		i -= len(m.Confirmer)
		copy(dAtA[i:], m.Confirmer)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Confirmer)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgConfirmNameResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgConfirmNameResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgConfirmNameResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func encodeVarintTx(dAtA []byte, offset int, v uint64) int {
	offset -= sovTx(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *MsgUpdateParams) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Authority)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = m.Params.Size()
	n += 1 + l + sovTx(uint64(l))
	return n
}

func (m *MsgUpdateParamsResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *MsgAttestDeposit) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Validator)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.Txid)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	if m.OpIndex != 0 {
		n += 1 + sovTx(uint64(m.OpIndex))
	}
	if m.SteemBlock != 0 {
		n += 1 + sovTx(uint64(m.SteemBlock))
	}
	l = len(m.SteemTimestamp)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.SteemSender)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.GatewayAccount)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	if m.AmountMillisteem != 0 {
		n += 1 + sovTx(uint64(m.AmountMillisteem))
	}
	l = len(m.Memo)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	if m.Asset != 0 {
		n += 1 + sovTx(uint64(m.Asset))
	}
	return n
}

func (m *MsgAttestDepositResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *MsgBridgeOut) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Sender)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.DestinationSteemAccount)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = m.AmountAsteem.Size()
	n += 1 + l + sovTx(uint64(l))
	l = len(m.Memo)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	if m.Asset != 0 {
		n += 1 + sovTx(uint64(m.Asset))
	}
	return n
}

func (m *MsgBridgeOutResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *MsgAttestWithdrawalPayout) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Validator)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	if m.WithdrawalId != 0 {
		n += 1 + sovTx(uint64(m.WithdrawalId))
	}
	l = len(m.SteemTxid)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	if m.OpIndex != 0 {
		n += 1 + sovTx(uint64(m.OpIndex))
	}
	if m.SteemBlock != 0 {
		n += 1 + sovTx(uint64(m.SteemBlock))
	}
	l = len(m.SteemTimestamp)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	if m.AmountMillisteem != 0 {
		n += 1 + sovTx(uint64(m.AmountMillisteem))
	}
	if m.Asset != 0 {
		n += 1 + sovTx(uint64(m.Asset))
	}
	return n
}

func (m *MsgAttestWithdrawalPayoutResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *MsgSubmitNameRegistration) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Validator)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.Txid)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	if m.OpIndex != 0 {
		n += 1 + sovTx(uint64(m.OpIndex))
	}
	if m.SteemBlock != 0 {
		n += 1 + sovTx(uint64(m.SteemBlock))
	}
	l = len(m.SteemTimestamp)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.SteemAccount)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.GatewayAccount)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	if m.AmountMillisteem != 0 {
		n += 1 + sovTx(uint64(m.AmountMillisteem))
	}
	l = len(m.Memo)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	return n
}

func (m *MsgSubmitNameRegistrationResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *MsgConfirmName) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Confirmer)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	if m.RegistrationId != 0 {
		n += 1 + sovTx(uint64(m.RegistrationId))
	}
	return n
}

func (m *MsgConfirmNameResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func sovTx(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozTx(x uint64) (n int) {
	return sovTx(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *MsgUpdateParams) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgUpdateParams: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgUpdateParams: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Authority", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Authority = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Params", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Params.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgUpdateParamsResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgUpdateParamsResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgUpdateParamsResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgAttestDeposit) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgAttestDeposit: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgAttestDeposit: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Validator", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Validator = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Txid", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Txid = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field OpIndex", wireType)
			}
			m.OpIndex = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.OpIndex |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field SteemBlock", wireType)
			}
			m.SteemBlock = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.SteemBlock |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field SteemTimestamp", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.SteemTimestamp = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field SteemSender", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.SteemSender = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 7:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field GatewayAccount", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.GatewayAccount = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 8:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field AmountMillisteem", wireType)
			}
			m.AmountMillisteem = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.AmountMillisteem |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 9:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Memo", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Memo = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 10:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Asset", wireType)
			}
			m.Asset = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Asset |= BridgeAsset(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgAttestDepositResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgAttestDepositResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgAttestDepositResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgBridgeOut) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgBridgeOut: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgBridgeOut: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Sender", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Sender = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field DestinationSteemAccount", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.DestinationSteemAccount = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field AmountAsteem", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.AmountAsteem.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Memo", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Memo = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 5:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Asset", wireType)
			}
			m.Asset = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Asset |= BridgeAsset(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgBridgeOutResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgBridgeOutResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgBridgeOutResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgAttestWithdrawalPayout) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgAttestWithdrawalPayout: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgAttestWithdrawalPayout: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Validator", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Validator = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field WithdrawalId", wireType)
			}
			m.WithdrawalId = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.WithdrawalId |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field SteemTxid", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.SteemTxid = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field OpIndex", wireType)
			}
			m.OpIndex = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.OpIndex |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 5:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field SteemBlock", wireType)
			}
			m.SteemBlock = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.SteemBlock |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field SteemTimestamp", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.SteemTimestamp = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 7:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field AmountMillisteem", wireType)
			}
			m.AmountMillisteem = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.AmountMillisteem |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 8:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Asset", wireType)
			}
			m.Asset = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Asset |= BridgeAsset(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgAttestWithdrawalPayoutResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgAttestWithdrawalPayoutResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgAttestWithdrawalPayoutResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgSubmitNameRegistration) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgSubmitNameRegistration: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgSubmitNameRegistration: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Validator", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Validator = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Txid", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Txid = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field OpIndex", wireType)
			}
			m.OpIndex = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.OpIndex |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field SteemBlock", wireType)
			}
			m.SteemBlock = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.SteemBlock |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field SteemTimestamp", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.SteemTimestamp = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field SteemAccount", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.SteemAccount = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 7:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field GatewayAccount", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.GatewayAccount = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 8:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field AmountMillisteem", wireType)
			}
			m.AmountMillisteem = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.AmountMillisteem |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 9:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Memo", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Memo = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgSubmitNameRegistrationResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgSubmitNameRegistrationResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgSubmitNameRegistrationResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgConfirmName) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgConfirmName: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgConfirmName: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Confirmer", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Confirmer = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field RegistrationId", wireType)
			}
			m.RegistrationId = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.RegistrationId |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgConfirmNameResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgConfirmNameResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgConfirmNameResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipTx(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowTx
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTx
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTx
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthTx
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupTx
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthTx
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthTx        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowTx          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupTx = fmt.Errorf("proto: unexpected end of group")
)
