// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: steemvm/steembridge/v1/withdrawal.proto

package types

import (
	cosmossdk_io_math "cosmossdk.io/math"
	fmt "fmt"
	_ "github.com/cosmos/gogoproto/gogoproto"
	proto "github.com/cosmos/gogoproto/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// WithdrawalStatus is the lifecycle status of a withdrawal. REQUESTED is the
// bridge-out request (funds already burned); PROCESSED means bonded validators
// have attested (2/3) that the gateway paid the user on Steem; REFUNDED means
// no attestation reached threshold within Params.WithdrawalTimeoutBlocks, so
// the net amount was automatically re-minted and returned to sender (no
// validator attestation required for the refund itself — see
// Keeper.RefundExpiredWithdrawals). Both PROCESSED and REFUNDED are terminal:
// once set, the other can never also occur for the same withdrawal.
type WithdrawalStatus int32

const (
	WithdrawalStatus_WITHDRAWAL_STATUS_REQUESTED WithdrawalStatus = 0
	WithdrawalStatus_WITHDRAWAL_STATUS_PROCESSED WithdrawalStatus = 1
	WithdrawalStatus_WITHDRAWAL_STATUS_REFUNDED  WithdrawalStatus = 2
)

var WithdrawalStatus_name = map[int32]string{
	0: "WITHDRAWAL_STATUS_REQUESTED",
	1: "WITHDRAWAL_STATUS_PROCESSED",
	2: "WITHDRAWAL_STATUS_REFUNDED",
}

var WithdrawalStatus_value = map[string]int32{
	"WITHDRAWAL_STATUS_REQUESTED": 0,
	"WITHDRAWAL_STATUS_PROCESSED": 1,
	"WITHDRAWAL_STATUS_REFUNDED":  2,
}

func (x WithdrawalStatus) String() string {
	return proto.EnumName(WithdrawalStatus_name, int32(x))
}

func (WithdrawalStatus) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_38df08baffdf45e0, []int{0}
}

// Withdrawal defines the Withdrawal message.
type Withdrawal struct {
	Id                      uint64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Sender                  string `protobuf:"bytes,2,opt,name=sender,proto3" json:"sender,omitempty"`
	DestinationSteemAccount string `protobuf:"bytes,3,opt,name=destination_steem_account,json=destinationSteemAccount,proto3" json:"destination_steem_account,omitempty"`
	// amount_asteem is the base-unit amount the sender burned (the DenomForAsset(asset)
	// amount; the field name is historical). amount_millisteem below is the NET payout.
	AmountAsteem cosmossdk_io_math.Int `protobuf:"bytes,4,opt,name=amount_asteem,json=amountAsteem,proto3,customtype=cosmossdk.io/math.Int" json:"amount_asteem"`
	// amount_millisteem is the NET Steem-side payout (gross minus the bridge fee).
	AmountMillisteem uint64           `protobuf:"varint,5,opt,name=amount_millisteem,json=amountMillisteem,proto3" json:"amount_millisteem,omitempty"`
	Memo             string           `protobuf:"bytes,6,opt,name=memo,proto3" json:"memo,omitempty"`
	BurnTxHash       string           `protobuf:"bytes,7,opt,name=burn_tx_hash,json=burnTxHash,proto3" json:"burn_tx_hash,omitempty"`
	Status           WithdrawalStatus `protobuf:"varint,8,opt,name=status,proto3,enum=steemvm.steembridge.v1.WithdrawalStatus" json:"status,omitempty"`
	CreatedAt        uint64           `protobuf:"varint,9,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	// asset is which native Steem asset this withdrawal pays out (STEEM/SBD).
	Asset BridgeAsset `protobuf:"varint,10,opt,name=asset,proto3,enum=steemvm.steembridge.v1.BridgeAsset" json:"asset,omitempty"`
	// fee_millisteem is the bridge fee withheld from the payout (gross - net).
	FeeMillisteem uint64 `protobuf:"varint,11,opt,name=fee_millisteem,json=feeMillisteem,proto3" json:"fee_millisteem,omitempty"`
	// steem_payout_txid / payout_op_index reference the gateway's Steem payout, set
	// when the withdrawal is marked PROCESSED.
	SteemPayoutTxid string `protobuf:"bytes,12,opt,name=steem_payout_txid,json=steemPayoutTxid,proto3" json:"steem_payout_txid,omitempty"`
	PayoutOpIndex   uint32 `protobuf:"varint,13,opt,name=payout_op_index,json=payoutOpIndex,proto3" json:"payout_op_index,omitempty"`
	ProcessedAt     uint64 `protobuf:"varint,14,opt,name=processed_at,json=processedAt,proto3" json:"processed_at,omitempty"`
	// validator_confirmations records the bonded validators that attested the payout.
	ValidatorConfirmations []*Confirmation `protobuf:"bytes,15,rep,name=validator_confirmations,json=validatorConfirmations,proto3" json:"validator_confirmations,omitempty"`
	// refunded_at is the SteemVM block height the automatic timeout refund ran,
	// set only when status becomes REFUNDED.
	RefundedAt uint64 `protobuf:"varint,16,opt,name=refunded_at,json=refundedAt,proto3" json:"refunded_at,omitempty"`
}

func (m *Withdrawal) Reset()         { *m = Withdrawal{} }
func (m *Withdrawal) String() string { return proto.CompactTextString(m) }
func (*Withdrawal) ProtoMessage()    {}
func (*Withdrawal) Descriptor() ([]byte, []int) {
	return fileDescriptor_38df08baffdf45e0, []int{0}
}
func (m *Withdrawal) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Withdrawal) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Withdrawal.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Withdrawal) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Withdrawal.Merge(m, src)
}
func (m *Withdrawal) XXX_Size() int {
	return m.Size()
}
func (m *Withdrawal) XXX_DiscardUnknown() {
	xxx_messageInfo_Withdrawal.DiscardUnknown(m)
}

var xxx_messageInfo_Withdrawal proto.InternalMessageInfo

func (m *Withdrawal) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Withdrawal) GetSender() string {
	if m != nil {
		return m.Sender
	}
	return ""
}

func (m *Withdrawal) GetDestinationSteemAccount() string {
	if m != nil {
		return m.DestinationSteemAccount
	}
	return ""
}

func (m *Withdrawal) GetAmountMillisteem() uint64 {
	if m != nil {
		return m.AmountMillisteem
	}
	return 0
}

func (m *Withdrawal) GetMemo() string {
	if m != nil {
		return m.Memo
	}
	return ""
}

func (m *Withdrawal) GetBurnTxHash() string {
	if m != nil {
		return m.BurnTxHash
	}
	return ""
}

func (m *Withdrawal) GetStatus() WithdrawalStatus {
	if m != nil {
		return m.Status
	}
	return WithdrawalStatus_WITHDRAWAL_STATUS_REQUESTED
}

func (m *Withdrawal) GetCreatedAt() uint64 {
	if m != nil {
		return m.CreatedAt
	}
	return 0
}

func (m *Withdrawal) GetAsset() BridgeAsset {
	if m != nil {
		return m.Asset
	}
	return BridgeAsset_BRIDGE_ASSET_STEEM
}

func (m *Withdrawal) GetFeeMillisteem() uint64 {
	if m != nil {
		return m.FeeMillisteem
	}
	return 0
}

func (m *Withdrawal) GetSteemPayoutTxid() string {
	if m != nil {
		return m.SteemPayoutTxid
	}
	return ""
}

func (m *Withdrawal) GetPayoutOpIndex() uint32 {
	if m != nil {
		return m.PayoutOpIndex
	}
	return 0
}

func (m *Withdrawal) GetProcessedAt() uint64 {
	if m != nil {
		return m.ProcessedAt
	}
	return 0
}

func (m *Withdrawal) GetValidatorConfirmations() []*Confirmation {
	if m != nil {
		return m.ValidatorConfirmations
	}
	return nil
}

func (m *Withdrawal) GetRefundedAt() uint64 {
	if m != nil {
		return m.RefundedAt
	}
	return 0
}

func init() {
	proto.RegisterEnum("steemvm.steembridge.v1.WithdrawalStatus", WithdrawalStatus_name, WithdrawalStatus_value)
	proto.RegisterType((*Withdrawal)(nil), "steemvm.steembridge.v1.Withdrawal")
}

func init() {
	proto.RegisterFile("steemvm/steembridge/v1/withdrawal.proto", fileDescriptor_38df08baffdf45e0)
}

var fileDescriptor_38df08baffdf45e0 = []byte{
	// 619 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x93, 0x4f, 0x4f, 0xdb, 0x4c,
	0x10, 0xc6, 0xe3, 0x00, 0x79, 0x5f, 0x26, 0x7f, 0x08, 0xab, 0x16, 0x5c, 0x2a, 0x9c, 0x94, 0xd2,
	0x36, 0xa2, 0x92, 0x2d, 0xe8, 0xa1, 0x6a, 0x4f, 0x75, 0x48, 0x2a, 0x90, 0xda, 0x42, 0xed, 0x20,
	0xa4, 0x4a, 0x95, 0xb5, 0x78, 0x37, 0x64, 0xd5, 0xd8, 0x6b, 0x79, 0x37, 0x21, 0x7c, 0x8b, 0x7e,
	0x2c, 0x8e, 0xf4, 0x56, 0xf5, 0x80, 0x2a, 0xf8, 0x22, 0x95, 0xd7, 0x26, 0xb5, 0xaa, 0xe4, 0xe4,
	0xf1, 0x33, 0xbf, 0x79, 0x76, 0xc6, 0xe3, 0x85, 0x17, 0x42, 0x52, 0x1a, 0x8c, 0x03, 0x4b, 0x3d,
	0xcf, 0x62, 0x46, 0xce, 0xa9, 0x35, 0xde, 0xb5, 0x2e, 0x98, 0x1c, 0x90, 0x18, 0x5f, 0xe0, 0xa1,
	0x19, 0xc5, 0x5c, 0x72, 0xb4, 0x96, 0x81, 0x66, 0x0e, 0x34, 0xc7, 0xbb, 0x1b, 0x0f, 0xce, 0xf9,
	0x39, 0x57, 0x88, 0x95, 0x44, 0x29, 0xbd, 0xb1, 0x35, 0xc7, 0x16, 0x0b, 0x41, 0x65, 0xc6, 0x6c,
	0xcf, 0x61, 0x08, 0x8d, 0xb8, 0x60, 0x19, 0xb5, 0xf5, 0x63, 0x09, 0xe0, 0x74, 0xda, 0x0c, 0xaa,
	0x41, 0x91, 0x11, 0x5d, 0x6b, 0x6a, 0xad, 0x45, 0xa7, 0xc8, 0x08, 0x5a, 0x83, 0x92, 0xa0, 0x21,
	0xa1, 0xb1, 0x5e, 0x6c, 0x6a, 0xad, 0x65, 0x27, 0x7b, 0x43, 0x6f, 0xe1, 0x11, 0xa1, 0x42, 0xb2,
	0x10, 0x4b, 0xc6, 0x43, 0x4f, 0x1d, 0xe1, 0x61, 0xdf, 0xe7, 0xa3, 0x50, 0xea, 0x0b, 0x0a, 0x5d,
	0xcf, 0x01, 0x6e, 0x92, 0xb7, 0xd3, 0x34, 0x6a, 0x43, 0x15, 0x07, 0x49, 0xe4, 0x61, 0x55, 0xa7,
	0x2f, 0x26, 0x7c, 0x7b, 0xf3, 0xea, 0xa6, 0x51, 0xf8, 0x75, 0xd3, 0x78, 0xe8, 0x73, 0x11, 0x70,
	0x21, 0xc8, 0x37, 0x93, 0x71, 0x2b, 0xc0, 0x72, 0x60, 0x1e, 0x86, 0xd2, 0xa9, 0xa4, 0x35, 0xb6,
	0x2a, 0x41, 0x2f, 0x61, 0x35, 0xf3, 0x08, 0xd8, 0x70, 0xc8, 0x52, 0x9f, 0x25, 0xd5, 0x76, 0x3d,
	0x4d, 0x7c, 0x9c, 0xea, 0x08, 0xc1, 0x62, 0x40, 0x03, 0xae, 0x97, 0x54, 0x5f, 0x2a, 0x46, 0x4d,
	0xa8, 0x9c, 0x8d, 0xe2, 0xd0, 0x93, 0x13, 0x6f, 0x80, 0xc5, 0x40, 0xff, 0x4f, 0xe5, 0x20, 0xd1,
	0x7a, 0x93, 0x03, 0x2c, 0x06, 0xe8, 0x1d, 0x94, 0x84, 0xc4, 0x72, 0x24, 0xf4, 0xff, 0x9b, 0x5a,
	0xab, 0xb6, 0xd7, 0x32, 0x67, 0xaf, 0xc8, 0xfc, 0xfb, 0xf9, 0x5c, 0xc5, 0x3b, 0x59, 0x1d, 0xda,
	0x04, 0xf0, 0x63, 0x8a, 0x25, 0x25, 0x1e, 0x96, 0xfa, 0xb2, 0xea, 0x6e, 0x39, 0x53, 0x6c, 0x89,
	0xde, 0xc0, 0x92, 0xda, 0x97, 0x0e, 0xca, 0xff, 0xe9, 0x3c, 0xff, 0xb6, 0x8a, 0xec, 0x04, 0x75,
	0xd2, 0x0a, 0xf4, 0x0c, 0x6a, 0x7d, 0x4a, 0xf3, 0xb3, 0x97, 0x95, 0x7b, 0xb5, 0x4f, 0x69, 0x6e,
	0xf0, 0x1d, 0x58, 0x4d, 0x37, 0x13, 0xe1, 0x4b, 0x3e, 0x92, 0x9e, 0x9c, 0x30, 0xa2, 0x57, 0xd4,
	0xa4, 0x2b, 0x2a, 0x71, 0xac, 0xf4, 0xde, 0x84, 0x11, 0xf4, 0x1c, 0x56, 0x32, 0x8a, 0x47, 0x1e,
	0x0b, 0x09, 0x9d, 0xe8, 0xd5, 0xa6, 0xd6, 0xaa, 0x3a, 0xd5, 0x54, 0x3e, 0x8a, 0x0e, 0x13, 0x11,
	0x3d, 0x81, 0x4a, 0x14, 0x73, 0x9f, 0x0a, 0x91, 0x8e, 0x55, 0x53, 0x07, 0x97, 0xa7, 0x9a, 0x2d,
	0xd1, 0x57, 0x58, 0x1f, 0xe3, 0x21, 0x23, 0x58, 0xf2, 0xd8, 0xf3, 0x79, 0xd8, 0x67, 0x71, 0xa0,
	0x7e, 0x03, 0xa1, 0xaf, 0x34, 0x17, 0x5a, 0xe5, 0xbd, 0xed, 0x79, 0xa3, 0xee, 0xe7, 0x60, 0x67,
	0x6d, 0x6a, 0x92, 0x97, 0x05, 0x6a, 0x40, 0x39, 0xa6, 0xfd, 0x51, 0x48, 0xd2, 0x06, 0xea, 0xaa,
	0x01, 0xb8, 0x97, 0x6c, 0xb9, 0x23, 0xa1, 0xfe, 0xef, 0x4e, 0x50, 0x03, 0x1e, 0x9f, 0x1e, 0xf6,
	0x0e, 0x3a, 0x8e, 0x7d, 0x6a, 0x7f, 0xf0, 0xdc, 0x9e, 0xdd, 0x3b, 0x71, 0x3d, 0xa7, 0xfb, 0xf9,
	0xa4, 0xeb, 0xf6, 0xba, 0x9d, 0x7a, 0x61, 0x36, 0x70, 0xec, 0x1c, 0xed, 0x77, 0x5d, 0xb7, 0xdb,
	0xa9, 0x6b, 0xc8, 0x80, 0x8d, 0x59, 0x0e, 0xef, 0x4f, 0x3e, 0x75, 0xba, 0x9d, 0x7a, 0xb1, 0xfd,
	0xfa, 0xea, 0xd6, 0xd0, 0xae, 0x6f, 0x0d, 0xed, 0xf7, 0xad, 0xa1, 0x7d, 0xbf, 0x33, 0x0a, 0xd7,
	0x77, 0x46, 0xe1, 0xe7, 0x9d, 0x51, 0xf8, 0xb2, 0x79, 0x7f, 0x13, 0x27, 0x16, 0x8f, 0xb1, 0x3f,
	0xa4, 0x56, 0x76, 0x1b, 0xe5, 0x65, 0x44, 0xc5, 0x59, 0x49, 0xdd, 0xc4, 0x57, 0x7f, 0x02, 0x00,
	0x00, 0xff, 0xff, 0x6f, 0xee, 0xb0, 0x32, 0x2c, 0x04, 0x00, 0x00,
}

func (m *Withdrawal) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Withdrawal) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Withdrawal) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.RefundedAt != 0 {
		i = encodeVarintWithdrawal(dAtA, i, uint64(m.RefundedAt))
		i--
		dAtA[i] = 0x1
		i--
		dAtA[i] = 0x80
	}
	if len(m.ValidatorConfirmations) > 0 {
		for iNdEx := len(m.ValidatorConfirmations) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.ValidatorConfirmations[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintWithdrawal(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x7a
		}
	}
	if m.ProcessedAt != 0 {
		i = encodeVarintWithdrawal(dAtA, i, uint64(m.ProcessedAt))
		i--
		dAtA[i] = 0x70
	}
	if m.PayoutOpIndex != 0 {
		i = encodeVarintWithdrawal(dAtA, i, uint64(m.PayoutOpIndex))
		i--
		dAtA[i] = 0x68
	}
	if len(m.SteemPayoutTxid) > 0 {
		i -= len(m.SteemPayoutTxid)
		copy(dAtA[i:], m.SteemPayoutTxid)
		i = encodeVarintWithdrawal(dAtA, i, uint64(len(m.SteemPayoutTxid)))
		i--
		dAtA[i] = 0x62
	}
	if m.FeeMillisteem != 0 {
		i = encodeVarintWithdrawal(dAtA, i, uint64(m.FeeMillisteem))
		i--
		dAtA[i] = 0x58
	}
	if m.Asset != 0 {
		i = encodeVarintWithdrawal(dAtA, i, uint64(m.Asset))
		i--
		dAtA[i] = 0x50
	}
	if m.CreatedAt != 0 {
		i = encodeVarintWithdrawal(dAtA, i, uint64(m.CreatedAt))
		i--
		dAtA[i] = 0x48
	}
	if m.Status != 0 {
		i = encodeVarintWithdrawal(dAtA, i, uint64(m.Status))
		i--
		dAtA[i] = 0x40
	}
	if len(m.BurnTxHash) > 0 {
		i -= len(m.BurnTxHash)
		copy(dAtA[i:], m.BurnTxHash)
		i = encodeVarintWithdrawal(dAtA, i, uint64(len(m.BurnTxHash)))
		i--
		dAtA[i] = 0x3a
	}
	if len(m.Memo) > 0 {
		i -= len(m.Memo)
		copy(dAtA[i:], m.Memo)
		i = encodeVarintWithdrawal(dAtA, i, uint64(len(m.Memo)))
		i--
		dAtA[i] = 0x32
	}
	if m.AmountMillisteem != 0 {
		i = encodeVarintWithdrawal(dAtA, i, uint64(m.AmountMillisteem))
		i--
		dAtA[i] = 0x28
	}
	{
		size := m.AmountAsteem.Size()
		i -= size
		if _, err := m.AmountAsteem.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintWithdrawal(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x22
	if len(m.DestinationSteemAccount) > 0 {
		i -= len(m.DestinationSteemAccount)
		copy(dAtA[i:], m.DestinationSteemAccount)
		i = encodeVarintWithdrawal(dAtA, i, uint64(len(m.DestinationSteemAccount)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.Sender) > 0 {
		i -= len(m.Sender)
		copy(dAtA[i:], m.Sender)
		i = encodeVarintWithdrawal(dAtA, i, uint64(len(m.Sender)))
		i--
		dAtA[i] = 0x12
	}
	if m.Id != 0 {
		i = encodeVarintWithdrawal(dAtA, i, uint64(m.Id))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func encodeVarintWithdrawal(dAtA []byte, offset int, v uint64) int {
	offset -= sovWithdrawal(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *Withdrawal) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Id != 0 {
		n += 1 + sovWithdrawal(uint64(m.Id))
	}
	l = len(m.Sender)
	if l > 0 {
		n += 1 + l + sovWithdrawal(uint64(l))
	}
	l = len(m.DestinationSteemAccount)
	if l > 0 {
		n += 1 + l + sovWithdrawal(uint64(l))
	}
	l = m.AmountAsteem.Size()
	n += 1 + l + sovWithdrawal(uint64(l))
	if m.AmountMillisteem != 0 {
		n += 1 + sovWithdrawal(uint64(m.AmountMillisteem))
	}
	l = len(m.Memo)
	if l > 0 {
		n += 1 + l + sovWithdrawal(uint64(l))
	}
	l = len(m.BurnTxHash)
	if l > 0 {
		n += 1 + l + sovWithdrawal(uint64(l))
	}
	if m.Status != 0 {
		n += 1 + sovWithdrawal(uint64(m.Status))
	}
	if m.CreatedAt != 0 {
		n += 1 + sovWithdrawal(uint64(m.CreatedAt))
	}
	if m.Asset != 0 {
		n += 1 + sovWithdrawal(uint64(m.Asset))
	}
	if m.FeeMillisteem != 0 {
		n += 1 + sovWithdrawal(uint64(m.FeeMillisteem))
	}
	l = len(m.SteemPayoutTxid)
	if l > 0 {
		n += 1 + l + sovWithdrawal(uint64(l))
	}
	if m.PayoutOpIndex != 0 {
		n += 1 + sovWithdrawal(uint64(m.PayoutOpIndex))
	}
	if m.ProcessedAt != 0 {
		n += 1 + sovWithdrawal(uint64(m.ProcessedAt))
	}
	if len(m.ValidatorConfirmations) > 0 {
		for _, e := range m.ValidatorConfirmations {
			l = e.Size()
			n += 1 + l + sovWithdrawal(uint64(l))
		}
	}
	if m.RefundedAt != 0 {
		n += 2 + sovWithdrawal(uint64(m.RefundedAt))
	}
	return n
}

func sovWithdrawal(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozWithdrawal(x uint64) (n int) {
	return sovWithdrawal(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *Withdrawal) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowWithdrawal
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Withdrawal: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Withdrawal: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Id", wireType)
			}
			m.Id = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowWithdrawal
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Id |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Sender", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowWithdrawal
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthWithdrawal
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthWithdrawal
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Sender = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field DestinationSteemAccount", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowWithdrawal
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthWithdrawal
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthWithdrawal
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.DestinationSteemAccount = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field AmountAsteem", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowWithdrawal
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthWithdrawal
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthWithdrawal
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.AmountAsteem.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 5:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field AmountMillisteem", wireType)
			}
			m.AmountMillisteem = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowWithdrawal
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.AmountMillisteem |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Memo", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowWithdrawal
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthWithdrawal
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthWithdrawal
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Memo = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 7:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field BurnTxHash", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowWithdrawal
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthWithdrawal
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthWithdrawal
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.BurnTxHash = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 8:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Status", wireType)
			}
			m.Status = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowWithdrawal
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Status |= WithdrawalStatus(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 9:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field CreatedAt", wireType)
			}
			m.CreatedAt = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowWithdrawal
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.CreatedAt |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 10:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Asset", wireType)
			}
			m.Asset = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowWithdrawal
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Asset |= BridgeAsset(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 11:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field FeeMillisteem", wireType)
			}
			m.FeeMillisteem = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowWithdrawal
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.FeeMillisteem |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 12:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field SteemPayoutTxid", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowWithdrawal
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthWithdrawal
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthWithdrawal
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.SteemPayoutTxid = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 13:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field PayoutOpIndex", wireType)
			}
			m.PayoutOpIndex = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowWithdrawal
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.PayoutOpIndex |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 14:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ProcessedAt", wireType)
			}
			m.ProcessedAt = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowWithdrawal
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.ProcessedAt |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 15:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ValidatorConfirmations", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowWithdrawal
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthWithdrawal
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthWithdrawal
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ValidatorConfirmations = append(m.ValidatorConfirmations, &Confirmation{})
			if err := m.ValidatorConfirmations[len(m.ValidatorConfirmations)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 16:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field RefundedAt", wireType)
			}
			m.RefundedAt = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowWithdrawal
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.RefundedAt |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipWithdrawal(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthWithdrawal
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipWithdrawal(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowWithdrawal
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowWithdrawal
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowWithdrawal
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthWithdrawal
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupWithdrawal
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthWithdrawal
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthWithdrawal        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowWithdrawal          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupWithdrawal = fmt.Errorf("proto: unexpected end of group")
)
