# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: steemvm/oracle/data/v1/params.proto
# Protobuf Python Version: 5.29.3
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    3,
    '',
    'steemvm/oracle/data/v1/params.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from amino import amino_pb2 as amino_dot_amino__pb2
from gogoproto import gogo_pb2 as gogoproto_dot_gogo__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n#steemvm/oracle/data/v1/params.proto\x12\x16steemvm.oracle.data.v1\x1a\x11\x61mino/amino.proto\x1a\x14gogoproto/gogo.proto\"\xc2\x02\n\x06Params\x12\x1f\n\x0bvote_period\x18\x01 \x01(\x04R\nvotePeriod\x12J\n\x0evote_threshold\x18\x02 \x01(\tB#\xc8\xde\x1f\x00\xda\xde\x1f\x1b\x63osmossdk.io/math.LegacyDecR\rvoteThreshold\x12\x44\n\x0breward_band\x18\x03 \x01(\tB#\xc8\xde\x1f\x00\xda\xde\x1f\x1b\x63osmossdk.io/math.LegacyDecR\nrewardBand\x12@\n\tmiss_band\x18\x04 \x01(\tB#\xc8\xde\x1f\x00\xda\xde\x1f\x1b\x63osmossdk.io/math.LegacyDecR\x08missBand\x12\x1c\n\twhitelist\x18\x05 \x03(\tR\twhitelist:%\xe8\xa0\x1f\x01\x8a\xe7\xb0*\x1csteemvm/x/oracle/data/ParamsB\x1dZ\x1bsteemvm/x/oracle/data/typesb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'steemvm.oracle.data.v1.params_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z\033steemvm/x/oracle/data/types'
  _globals['_PARAMS'].fields_by_name['vote_threshold']._loaded_options = None
  _globals['_PARAMS'].fields_by_name['vote_threshold']._serialized_options = b'\310\336\037\000\332\336\037\033cosmossdk.io/math.LegacyDec'
  _globals['_PARAMS'].fields_by_name['reward_band']._loaded_options = None
  _globals['_PARAMS'].fields_by_name['reward_band']._serialized_options = b'\310\336\037\000\332\336\037\033cosmossdk.io/math.LegacyDec'
  _globals['_PARAMS'].fields_by_name['miss_band']._loaded_options = None
  _globals['_PARAMS'].fields_by_name['miss_band']._serialized_options = b'\310\336\037\000\332\336\037\033cosmossdk.io/math.LegacyDec'
  _globals['_PARAMS']._loaded_options = None
  _globals['_PARAMS']._serialized_options = b'\350\240\037\001\212\347\260*\034steemvm/x/oracle/data/Params'
  _globals['_PARAMS']._serialized_start=105
  _globals['_PARAMS']._serialized_end=427
# @@protoc_insertion_point(module_scope)
