# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: steemvm/steembridge/v1/asset.proto
# Protobuf Python Version: 5.29.3
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    3,
    '',
    'steemvm/steembridge/v1/asset.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\"steemvm/steembridge/v1/asset.proto\x12\x16steemvm.steembridge.v1*;\n\x0b\x42ridgeAsset\x12\x16\n\x12\x42RIDGE_ASSET_STEEM\x10\x00\x12\x14\n\x10\x42RIDGE_ASSET_SBD\x10\x01\x42\x1fZ\x1dsteemvm/x/oracle/bridge/typesb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'steemvm.steembridge.v1.asset_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z\035steemvm/x/oracle/bridge/types'
  _globals['_BRIDGEASSET']._serialized_start=62
  _globals['_BRIDGEASSET']._serialized_end=121
# @@protoc_insertion_point(module_scope)
