// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.12.0
//   protoc               unknown
// source: steemvm/oracle/data/v1/tx.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";
import Long from "long";

export const protobufPackage = "steemvm.oracle.data.v1";

/** MsgAggregateExchangeRatePrevote commits a hash of the vote to be revealed. */
export interface MsgAggregateExchangeRatePrevote {
  /** validator is the bech32 operator address of the voting validator. */
  validator: string;
  /** hash is the truncated hex commit hash of (salt, exchange_rates, validator). */
  hash: string;
}

/**
 * MsgAggregateExchangeRateVote reveals the salt and exchange rates that match a
 * previously committed prevote hash.
 */
export interface MsgAggregateExchangeRateVote {
  /** validator is the bech32 operator address of the voting validator. */
  validator: string;
  /** salt is the reveal salt used to compute the prevote hash. */
  salt: string;
  /**
   * exchange_rates is a comma-separated list of "PAIR:rate" entries,
   * e.g. "STEEM/USD:1.23,STEEM/SBD:0.98".
   */
  exchangeRates: string;
}

function createBaseMsgAggregateExchangeRatePrevote(): MsgAggregateExchangeRatePrevote {
  return { validator: "", hash: "" };
}

export const MsgAggregateExchangeRatePrevote: MessageFns<MsgAggregateExchangeRatePrevote> = {
  encode(message: MsgAggregateExchangeRatePrevote, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.validator !== "") {
      writer.uint32(10).string(message.validator);
    }
    if (message.hash !== "") {
      writer.uint32(18).string(message.hash);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): MsgAggregateExchangeRatePrevote {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseMsgAggregateExchangeRatePrevote();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.validator = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.hash = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): MsgAggregateExchangeRatePrevote {
    return {
      validator: isSet(object.validator) ? globalThis.String(object.validator) : "",
      hash: isSet(object.hash) ? globalThis.String(object.hash) : "",
    };
  },

  toJSON(message: MsgAggregateExchangeRatePrevote): unknown {
    const obj: any = {};
    if (message.validator !== "") {
      obj.validator = message.validator;
    }
    if (message.hash !== "") {
      obj.hash = message.hash;
    }
    return obj;
  },

  create(base?: DeepPartial<MsgAggregateExchangeRatePrevote>): MsgAggregateExchangeRatePrevote {
    return MsgAggregateExchangeRatePrevote.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<MsgAggregateExchangeRatePrevote>): MsgAggregateExchangeRatePrevote {
    const message = createBaseMsgAggregateExchangeRatePrevote();
    message.validator = object.validator ?? "";
    message.hash = object.hash ?? "";
    return message;
  },
};

function createBaseMsgAggregateExchangeRateVote(): MsgAggregateExchangeRateVote {
  return { validator: "", salt: "", exchangeRates: "" };
}

export const MsgAggregateExchangeRateVote: MessageFns<MsgAggregateExchangeRateVote> = {
  encode(message: MsgAggregateExchangeRateVote, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.validator !== "") {
      writer.uint32(10).string(message.validator);
    }
    if (message.salt !== "") {
      writer.uint32(18).string(message.salt);
    }
    if (message.exchangeRates !== "") {
      writer.uint32(26).string(message.exchangeRates);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): MsgAggregateExchangeRateVote {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseMsgAggregateExchangeRateVote();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.validator = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.salt = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.exchangeRates = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): MsgAggregateExchangeRateVote {
    return {
      validator: isSet(object.validator) ? globalThis.String(object.validator) : "",
      salt: isSet(object.salt) ? globalThis.String(object.salt) : "",
      exchangeRates: isSet(object.exchangeRates)
        ? globalThis.String(object.exchangeRates)
        : isSet(object.exchange_rates)
        ? globalThis.String(object.exchange_rates)
        : "",
    };
  },

  toJSON(message: MsgAggregateExchangeRateVote): unknown {
    const obj: any = {};
    if (message.validator !== "") {
      obj.validator = message.validator;
    }
    if (message.salt !== "") {
      obj.salt = message.salt;
    }
    if (message.exchangeRates !== "") {
      obj.exchangeRates = message.exchangeRates;
    }
    return obj;
  },

  create(base?: DeepPartial<MsgAggregateExchangeRateVote>): MsgAggregateExchangeRateVote {
    return MsgAggregateExchangeRateVote.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<MsgAggregateExchangeRateVote>): MsgAggregateExchangeRateVote {
    const message = createBaseMsgAggregateExchangeRateVote();
    message.validator = object.validator ?? "";
    message.salt = object.salt ?? "";
    message.exchangeRates = object.exchangeRates ?? "";
    return message;
  },
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends Long ? string | number | Long : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create(base?: DeepPartial<T>): T;
  fromPartial(object: DeepPartial<T>): T;
}
