# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: cosmos/evm/crypto/v1/ethsecp256k1/keys.proto
# Protobuf Python Version: 5.29.3
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    3,
    '',
    'cosmos/evm/crypto/v1/ethsecp256k1/keys.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from gogoproto import gogo_pb2 as gogoproto_dot_gogo__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n,cosmos/evm/crypto/v1/ethsecp256k1/keys.proto\x12!cosmos.evm.crypto.v1.ethsecp256k1\x1a\x14gogoproto/gogo.proto\" \n\x06PubKey\x12\x10\n\x03key\x18\x01 \x01(\x0cR\x03key:\x04\x98\xa0\x1f\x00\"\x1b\n\x07PrivKey\x12\x10\n\x03key\x18\x01 \x01(\x0cR\x03keyB+Z)github.com/cosmos/evm/crypto/ethsecp256k1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'cosmos.evm.crypto.v1.ethsecp256k1.keys_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z)github.com/cosmos/evm/crypto/ethsecp256k1'
  _globals['_PUBKEY']._loaded_options = None
  _globals['_PUBKEY']._serialized_options = b'\230\240\037\000'
  _globals['_PUBKEY']._serialized_start=105
  _globals['_PUBKEY']._serialized_end=137
  _globals['_PRIVKEY']._serialized_start=139
  _globals['_PRIVKEY']._serialized_end=166
# @@protoc_insertion_point(module_scope)
