# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: steemvm/oracle_client/v1/codegen_shim.proto
# Protobuf Python Version: 5.29.3
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    3,
    '',
    'steemvm/oracle_client/v1/codegen_shim.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from cosmos.tx.v1beta1 import tx_pb2 as cosmos_dot_tx_dot_v1beta1_dot_tx__pb2
from cosmos.evm.crypto.v1.ethsecp256k1 import keys_pb2 as cosmos_dot_evm_dot_crypto_dot_v1_dot_ethsecp256k1_dot_keys__pb2
from google.protobuf import any_pb2 as google_dot_protobuf_dot_any__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n+steemvm/oracle_client/v1/codegen_shim.proto\x12\x18steemvm.oracle_client.v1\x1a\x1a\x63osmos/tx/v1beta1/tx.proto\x1a,cosmos/evm/crypto/v1/ethsecp256k1/keys.proto\x1a\x19google/protobuf/any.protoB\x1cZ\x1asteemvm/oracle_client_shimb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'steemvm.oracle_client.v1.codegen_shim_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z\032steemvm/oracle_client_shim'
# @@protoc_insertion_point(module_scope)
