// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: steemvm/oracle/v1/params.proto

package types

import (
	cosmossdk_io_math "cosmossdk.io/math"
	fmt "fmt"
	_ "github.com/cosmos/cosmos-sdk/types/tx/amino"
	_ "github.com/cosmos/gogoproto/gogoproto"
	proto "github.com/cosmos/gogoproto/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// Params defines the parameters of the parent x/oracle unified slashing engine.
// Price-specific params (vote_period, whitelist, bands) live in x/oracle/data;
// these are the SHARED slashing/reward params both duties are judged by (§2b).
type Params struct {
	// slash_window is the number of blocks between evaluations. The combined
	// per-validator counter is tallied continuously and judged once per window.
	SlashWindow uint64 `protobuf:"varint,1,opt,name=slash_window,json=slashWindow,proto3" json:"slash_window,omitempty"`
	// slash_fraction is the fraction of a validator's stake slashed when it fails
	// the window (also jailed).
	SlashFraction cosmossdk_io_math.LegacyDec `protobuf:"bytes,2,opt,name=slash_fraction,json=slashFraction,proto3,customtype=cosmossdk.io/math.LegacyDec" json:"slash_fraction"`
	// min_valid_per_window is the minimum combined weighted participation score a
	// validator must reach over the window to avoid a slash.
	MinValidPerWindow cosmossdk_io_math.LegacyDec `protobuf:"bytes,3,opt,name=min_valid_per_window,json=minValidPerWindow,proto3,customtype=cosmossdk.io/math.LegacyDec" json:"min_valid_per_window"`
	// w_price and w_bridge weight the two duties in the combined score. They are
	// renormalized over whichever duties were active in the window.
	WPrice  cosmossdk_io_math.LegacyDec `protobuf:"bytes,4,opt,name=w_price,json=wPrice,proto3,customtype=cosmossdk.io/math.LegacyDec" json:"w_price"`
	WBridge cosmossdk_io_math.LegacyDec `protobuf:"bytes,5,opt,name=w_bridge,json=wBridge,proto3,customtype=cosmossdk.io/math.LegacyDec" json:"w_bridge"`
	// duty_floor is the anti-masking guard: any ACTIVE duty whose rate is at or
	// below this is slashed regardless of the combined score (default 0 → a
	// validator that attested none of an active duty is always slashed).
	DutyFloor cosmossdk_io_math.LegacyDec `protobuf:"bytes,6,opt,name=duty_floor,json=dutyFloor,proto3,customtype=cosmossdk.io/math.LegacyDec" json:"duty_floor"`
	// reward_distribution_window is the block span over which performance rewards
	// are averaged (rewards themselves are deferred; the field is carried now).
	RewardDistributionWindow uint64 `protobuf:"varint,7,opt,name=reward_distribution_window,json=rewardDistributionWindow,proto3" json:"reward_distribution_window,omitempty"`
	// bridge_grace_blocks is how long after a bridge event finalizes a validator
	// may still attest and be counted as a hit (absorbs brief RPC blips).
	BridgeGraceBlocks uint64 `protobuf:"varint,8,opt,name=bridge_grace_blocks,json=bridgeGraceBlocks,proto3" json:"bridge_grace_blocks,omitempty"`
}

func (m *Params) Reset()         { *m = Params{} }
func (m *Params) String() string { return proto.CompactTextString(m) }
func (*Params) ProtoMessage()    {}
func (*Params) Descriptor() ([]byte, []int) {
	return fileDescriptor_13bca7ff70e0030e, []int{0}
}
func (m *Params) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Params) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Params.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Params) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Params.Merge(m, src)
}
func (m *Params) XXX_Size() int {
	return m.Size()
}
func (m *Params) XXX_DiscardUnknown() {
	xxx_messageInfo_Params.DiscardUnknown(m)
}

var xxx_messageInfo_Params proto.InternalMessageInfo

func (m *Params) GetSlashWindow() uint64 {
	if m != nil {
		return m.SlashWindow
	}
	return 0
}

func (m *Params) GetRewardDistributionWindow() uint64 {
	if m != nil {
		return m.RewardDistributionWindow
	}
	return 0
}

func (m *Params) GetBridgeGraceBlocks() uint64 {
	if m != nil {
		return m.BridgeGraceBlocks
	}
	return 0
}

func init() {
	proto.RegisterType((*Params)(nil), "steemvm.oracle.v1.Params")
}

func init() { proto.RegisterFile("steemvm/oracle/v1/params.proto", fileDescriptor_13bca7ff70e0030e) }

var fileDescriptor_13bca7ff70e0030e = []byte{
	// 411 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x92, 0xcf, 0xaa, 0xd3, 0x40,
	0x18, 0xc5, 0x13, 0xad, 0xe9, 0xbd, 0xe3, 0x1f, 0x48, 0x2c, 0x1a, 0x2a, 0xa4, 0x55, 0x37, 0xc5,
	0x45, 0x62, 0x71, 0x27, 0xc5, 0x45, 0x28, 0x15, 0xc4, 0x45, 0x29, 0xa2, 0xe0, 0x66, 0x98, 0x4c,
	0xa6, 0xe9, 0xd0, 0x4c, 0x26, 0xcc, 0xa4, 0x89, 0x7d, 0x05, 0x57, 0xbe, 0x81, 0x3e, 0x82, 0x8f,
	0xd1, 0x65, 0x97, 0xe2, 0xa2, 0x48, 0xbb, 0xd0, 0xc7, 0x90, 0xcc, 0x24, 0x20, 0xb8, 0xc9, 0x26,
	0x0c, 0xdf, 0x39, 0xbf, 0x93, 0xc9, 0x97, 0x03, 0x3c, 0x59, 0x10, 0xc2, 0x4a, 0x16, 0x70, 0x81,
	0x70, 0x4a, 0x82, 0x72, 0x1a, 0xe4, 0x48, 0x20, 0x26, 0xfd, 0x5c, 0xf0, 0x82, 0x3b, 0x76, 0xa3,
	0xfb, 0x5a, 0xf7, 0xcb, 0xe9, 0xd0, 0x46, 0x8c, 0x66, 0x3c, 0x50, 0x4f, 0xed, 0x1a, 0x0e, 0x12,
	0x9e, 0x70, 0x75, 0x0c, 0xea, 0x93, 0x9e, 0x3e, 0xf9, 0xda, 0x03, 0xd6, 0x52, 0x85, 0x39, 0x8f,
	0xc1, 0x1d, 0x99, 0x22, 0xb9, 0x81, 0x15, 0xcd, 0x62, 0x5e, 0xb9, 0xe6, 0xd8, 0x9c, 0xf4, 0x56,
	0xb7, 0xd5, 0xec, 0x83, 0x1a, 0x39, 0x6f, 0xc0, 0x3d, 0x6d, 0x59, 0x0b, 0x84, 0x0b, 0xca, 0x33,
	0xf7, 0xc6, 0xd8, 0x9c, 0x5c, 0x87, 0x4f, 0x0f, 0xa7, 0x91, 0xf1, 0xf3, 0x34, 0x7a, 0x84, 0xb9,
	0x64, 0x5c, 0xca, 0x78, 0xeb, 0x53, 0x1e, 0x30, 0x54, 0x6c, 0xfc, 0xb7, 0x24, 0x41, 0x78, 0x3f,
	0x27, 0x78, 0x75, 0x57, 0xa1, 0x8b, 0x86, 0x74, 0xde, 0x81, 0x01, 0xa3, 0x19, 0x2c, 0x51, 0x4a,
	0x63, 0x98, 0x13, 0xd1, 0xbe, 0xf6, 0x66, 0xf7, 0x44, 0x9b, 0xd1, 0xec, 0x7d, 0xcd, 0x2f, 0x89,
	0x68, 0x6e, 0x38, 0x03, 0xfd, 0x0a, 0xe6, 0x82, 0x62, 0xe2, 0xf6, 0xba, 0x07, 0x59, 0xd5, 0xb2,
	0x46, 0x9c, 0x57, 0xe0, 0xaa, 0x82, 0x91, 0xa0, 0x71, 0x42, 0xdc, 0x5b, 0xdd, 0xf1, 0x7e, 0x15,
	0x2a, 0xc6, 0x09, 0x01, 0x88, 0x77, 0xc5, 0x1e, 0xae, 0x53, 0xce, 0x85, 0x6b, 0x75, 0x4f, 0xb8,
	0xae, 0xb1, 0x45, 0x4d, 0x39, 0x33, 0x30, 0x14, 0xa4, 0x42, 0x22, 0x86, 0x31, 0x95, 0x85, 0xa0,
	0xd1, 0xae, 0x5e, 0x57, 0xbb, 0x9d, 0xbe, 0xfa, 0x29, 0xae, 0x76, 0xcc, 0xff, 0x31, 0x34, 0xdf,
	0xef, 0x83, 0xfb, 0xfa, 0xfe, 0x30, 0x11, 0x08, 0x13, 0x18, 0xa5, 0x1c, 0x6f, 0xa5, 0x7b, 0xa5,
	0x30, 0x5b, 0x4b, 0xaf, 0x6b, 0x25, 0x54, 0xc2, 0xcb, 0xf1, 0x9f, 0x6f, 0x23, 0xf3, 0xf3, 0xef,
	0xef, 0xcf, 0x1e, 0xb6, 0x25, 0xfb, 0xd4, 0xd6, 0x4c, 0xd7, 0x22, 0x7c, 0x7e, 0x38, 0x7b, 0xe6,
	0xf1, 0xec, 0x99, 0xbf, 0xce, 0x9e, 0xf9, 0xe5, 0xe2, 0x19, 0xc7, 0x8b, 0x67, 0xfc, 0xb8, 0x78,
	0xc6, 0xc7, 0x07, 0xff, 0x21, 0xc5, 0x3e, 0x27, 0x32, 0xb2, 0x54, 0xb5, 0x5e, 0xfc, 0x0d, 0x00,
	0x00, 0xff, 0xff, 0x80, 0xa1, 0x0c, 0xfb, 0xb8, 0x02, 0x00, 0x00,
}

func (this *Params) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*Params)
	if !ok {
		that2, ok := that.(Params)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if this.SlashWindow != that1.SlashWindow {
		return false
	}
	if !this.SlashFraction.Equal(that1.SlashFraction) {
		return false
	}
	if !this.MinValidPerWindow.Equal(that1.MinValidPerWindow) {
		return false
	}
	if !this.WPrice.Equal(that1.WPrice) {
		return false
	}
	if !this.WBridge.Equal(that1.WBridge) {
		return false
	}
	if !this.DutyFloor.Equal(that1.DutyFloor) {
		return false
	}
	if this.RewardDistributionWindow != that1.RewardDistributionWindow {
		return false
	}
	if this.BridgeGraceBlocks != that1.BridgeGraceBlocks {
		return false
	}
	return true
}
func (m *Params) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Params) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Params) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.BridgeGraceBlocks != 0 {
		i = encodeVarintParams(dAtA, i, uint64(m.BridgeGraceBlocks))
		i--
		dAtA[i] = 0x40
	}
	if m.RewardDistributionWindow != 0 {
		i = encodeVarintParams(dAtA, i, uint64(m.RewardDistributionWindow))
		i--
		dAtA[i] = 0x38
	}
	{
		size := m.DutyFloor.Size()
		i -= size
		if _, err := m.DutyFloor.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintParams(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x32
	{
		size := m.WBridge.Size()
		i -= size
		if _, err := m.WBridge.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintParams(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x2a
	{
		size := m.WPrice.Size()
		i -= size
		if _, err := m.WPrice.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintParams(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x22
	{
		size := m.MinValidPerWindow.Size()
		i -= size
		if _, err := m.MinValidPerWindow.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintParams(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x1a
	{
		size := m.SlashFraction.Size()
		i -= size
		if _, err := m.SlashFraction.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintParams(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x12
	if m.SlashWindow != 0 {
		i = encodeVarintParams(dAtA, i, uint64(m.SlashWindow))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func encodeVarintParams(dAtA []byte, offset int, v uint64) int {
	offset -= sovParams(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *Params) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.SlashWindow != 0 {
		n += 1 + sovParams(uint64(m.SlashWindow))
	}
	l = m.SlashFraction.Size()
	n += 1 + l + sovParams(uint64(l))
	l = m.MinValidPerWindow.Size()
	n += 1 + l + sovParams(uint64(l))
	l = m.WPrice.Size()
	n += 1 + l + sovParams(uint64(l))
	l = m.WBridge.Size()
	n += 1 + l + sovParams(uint64(l))
	l = m.DutyFloor.Size()
	n += 1 + l + sovParams(uint64(l))
	if m.RewardDistributionWindow != 0 {
		n += 1 + sovParams(uint64(m.RewardDistributionWindow))
	}
	if m.BridgeGraceBlocks != 0 {
		n += 1 + sovParams(uint64(m.BridgeGraceBlocks))
	}
	return n
}

func sovParams(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozParams(x uint64) (n int) {
	return sovParams(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *Params) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowParams
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Params: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Params: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field SlashWindow", wireType)
			}
			m.SlashWindow = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.SlashWindow |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field SlashFraction", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthParams
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthParams
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.SlashFraction.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field MinValidPerWindow", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthParams
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthParams
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.MinValidPerWindow.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field WPrice", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthParams
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthParams
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.WPrice.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field WBridge", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthParams
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthParams
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.WBridge.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field DutyFloor", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthParams
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthParams
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.DutyFloor.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 7:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field RewardDistributionWindow", wireType)
			}
			m.RewardDistributionWindow = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.RewardDistributionWindow |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 8:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field BridgeGraceBlocks", wireType)
			}
			m.BridgeGraceBlocks = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.BridgeGraceBlocks |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipParams(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthParams
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipParams(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowParams
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowParams
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowParams
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthParams
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupParams
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthParams
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthParams        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowParams          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupParams = fmt.Errorf("proto: unexpected end of group")
)
