// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: steemvm/steembridge/v1/params.proto

package types

import (
	cosmossdk_io_math "cosmossdk.io/math"
	fmt "fmt"
	_ "github.com/cosmos/cosmos-sdk/types/tx/amino"
	_ "github.com/cosmos/gogoproto/gogoproto"
	proto "github.com/cosmos/gogoproto/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// Params defines the parameters for the module.
type Params struct {
	BridgeEnabled               bool                        `protobuf:"varint,1,opt,name=bridge_enabled,json=bridgeEnabled,proto3" json:"bridge_enabled,omitempty"`
	BridgeOutEnabled            bool                        `protobuf:"varint,2,opt,name=bridge_out_enabled,json=bridgeOutEnabled,proto3" json:"bridge_out_enabled,omitempty"`
	GatewayAccount              string                      `protobuf:"bytes,3,opt,name=gateway_account,json=gatewayAccount,proto3" json:"gateway_account,omitempty"`
	BridgeConfirmationThreshold cosmossdk_io_math.LegacyDec `protobuf:"bytes,4,opt,name=bridge_confirmation_threshold,json=bridgeConfirmationThreshold,proto3,customtype=cosmossdk.io/math.LegacyDec" json:"bridge_confirmation_threshold"`
	MinimumBridgeAmount         uint64                      `protobuf:"varint,5,opt,name=minimum_bridge_amount,json=minimumBridgeAmount,proto3" json:"minimum_bridge_amount,omitempty"`
	MaximumBridgeAmount         uint64                      `protobuf:"varint,6,opt,name=maximum_bridge_amount,json=maximumBridgeAmount,proto3" json:"maximum_bridge_amount,omitempty"`
	DepositTimeoutBlocks        uint64                      `protobuf:"varint,7,opt,name=deposit_timeout_blocks,json=depositTimeoutBlocks,proto3" json:"deposit_timeout_blocks,omitempty"`
	// name_service_enabled gates the Steem name-service flow (MsgSubmitNameRegistration /
	// MsgConfirmName). Independent of bridge_enabled; both features share gateway_account.
	NameServiceEnabled bool `protobuf:"varint,8,opt,name=name_service_enabled,json=nameServiceEnabled,proto3" json:"name_service_enabled,omitempty"`
	// name_registration_min_millisteem is the minimum Steem-side payment for a
	// name registration, in millisteem (1 = 0.001 STEEM).
	NameRegistrationMinMillisteem uint64 `protobuf:"varint,9,opt,name=name_registration_min_millisteem,json=nameRegistrationMinMillisteem,proto3" json:"name_registration_min_millisteem,omitempty"`
	// name_pending_timeout_blocks bounds both attestation (PENDING) and user
	// confirmation (AWAITING_CONFIRMATION) phases; the window restarts when the
	// registration reaches threshold.
	NamePendingTimeoutBlocks uint64 `protobuf:"varint,10,opt,name=name_pending_timeout_blocks,json=namePendingTimeoutBlocks,proto3" json:"name_pending_timeout_blocks,omitempty"`
	// relayer_start_block is the Steem block from which validator relayers
	// begin scanning on first run, giving every validator the same anchor
	// regardless of when its node first starts (typically the Steem last
	// irreversible block recorded at chain launch). 0 means each relayer
	// starts at Steem's LIB when it first boots. Advisory for relayers only —
	// consensus logic never reads it. Governance may move it forward to spare
	// newly joining validators a long backfill.
	RelayerStartBlock uint64 `protobuf:"varint,11,opt,name=relayer_start_block,json=relayerStartBlock,proto3" json:"relayer_start_block,omitempty"`
}

func (m *Params) Reset()         { *m = Params{} }
func (m *Params) String() string { return proto.CompactTextString(m) }
func (*Params) ProtoMessage()    {}
func (*Params) Descriptor() ([]byte, []int) {
	return fileDescriptor_6f3b7f0c19b2a2e2, []int{0}
}
func (m *Params) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Params) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Params.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Params) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Params.Merge(m, src)
}
func (m *Params) XXX_Size() int {
	return m.Size()
}
func (m *Params) XXX_DiscardUnknown() {
	xxx_messageInfo_Params.DiscardUnknown(m)
}

var xxx_messageInfo_Params proto.InternalMessageInfo

func (m *Params) GetBridgeEnabled() bool {
	if m != nil {
		return m.BridgeEnabled
	}
	return false
}

func (m *Params) GetBridgeOutEnabled() bool {
	if m != nil {
		return m.BridgeOutEnabled
	}
	return false
}

func (m *Params) GetGatewayAccount() string {
	if m != nil {
		return m.GatewayAccount
	}
	return ""
}

func (m *Params) GetMinimumBridgeAmount() uint64 {
	if m != nil {
		return m.MinimumBridgeAmount
	}
	return 0
}

func (m *Params) GetMaximumBridgeAmount() uint64 {
	if m != nil {
		return m.MaximumBridgeAmount
	}
	return 0
}

func (m *Params) GetDepositTimeoutBlocks() uint64 {
	if m != nil {
		return m.DepositTimeoutBlocks
	}
	return 0
}

func (m *Params) GetNameServiceEnabled() bool {
	if m != nil {
		return m.NameServiceEnabled
	}
	return false
}

func (m *Params) GetNameRegistrationMinMillisteem() uint64 {
	if m != nil {
		return m.NameRegistrationMinMillisteem
	}
	return 0
}

func (m *Params) GetNamePendingTimeoutBlocks() uint64 {
	if m != nil {
		return m.NamePendingTimeoutBlocks
	}
	return 0
}

func (m *Params) GetRelayerStartBlock() uint64 {
	if m != nil {
		return m.RelayerStartBlock
	}
	return 0
}

func init() {
	proto.RegisterType((*Params)(nil), "steemvm.steembridge.v1.Params")
}

func init() {
	proto.RegisterFile("steemvm/steembridge/v1/params.proto", fileDescriptor_6f3b7f0c19b2a2e2)
}

var fileDescriptor_6f3b7f0c19b2a2e2 = []byte{
	// 503 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x92, 0xcf, 0x6e, 0xd3, 0x40,
	0x10, 0xc6, 0x63, 0x68, 0x43, 0xbb, 0x88, 0x42, 0xdd, 0x50, 0x59, 0x0d, 0x75, 0x22, 0xaa, 0x8a,
	0x08, 0x21, 0x9b, 0xf2, 0xe7, 0x82, 0xc4, 0xa1, 0x01, 0xc4, 0x85, 0x8a, 0x2a, 0xed, 0x89, 0x8b,
	0xb5, 0xb1, 0x07, 0x67, 0x55, 0xef, 0xae, 0xb5, 0xbb, 0x09, 0xcd, 0x2b, 0x70, 0xe2, 0x09, 0x10,
	0x8f, 0xc0, 0x63, 0xf4, 0xd8, 0x23, 0xe2, 0x50, 0xa1, 0xe4, 0x00, 0x8f, 0x81, 0x3c, 0xbb, 0x29,
	0x09, 0xea, 0xc1, 0xf6, 0x6a, 0xbe, 0xdf, 0xf7, 0xed, 0x68, 0x3c, 0x64, 0x47, 0x1b, 0x00, 0x3e,
	0xe2, 0x31, 0x7e, 0xfb, 0x8a, 0x65, 0x39, 0xc4, 0xa3, 0xbd, 0xb8, 0xa4, 0x8a, 0x72, 0x1d, 0x95,
	0x4a, 0x1a, 0xe9, 0x6f, 0x3a, 0x28, 0x9a, 0x83, 0xa2, 0xd1, 0xde, 0xd6, 0x3a, 0xe5, 0x4c, 0xc8,
	0x18, 0xdf, 0x16, 0xdd, 0x6a, 0xe4, 0x32, 0x97, 0x78, 0x8c, 0xab, 0x93, 0xad, 0xde, 0xff, 0xba,
	0x4c, 0xea, 0x87, 0x98, 0xe8, 0xef, 0x92, 0x35, 0x1b, 0x90, 0x80, 0xa0, 0xfd, 0x02, 0xb2, 0xc0,
	0x6b, 0x7b, 0x9d, 0x95, 0xde, 0x2d, 0x5b, 0x7d, 0x63, 0x8b, 0xfe, 0x23, 0xe2, 0x3b, 0x4c, 0x0e,
	0xcd, 0x25, 0x7a, 0x0d, 0xd1, 0x3b, 0x56, 0x79, 0x3f, 0x34, 0x33, 0xfa, 0x01, 0xb9, 0x9d, 0x53,
	0x03, 0x9f, 0xe8, 0x38, 0xa1, 0x69, 0x2a, 0x87, 0xc2, 0x04, 0xd7, 0xdb, 0x5e, 0x67, 0xb5, 0xb7,
	0xe6, 0xca, 0xfb, 0xb6, 0xea, 0xe7, 0x64, 0xdb, 0xc5, 0xa6, 0x52, 0x7c, 0x64, 0x8a, 0x53, 0xc3,
	0xa4, 0x48, 0xcc, 0x40, 0x81, 0x1e, 0xc8, 0x22, 0x0b, 0x96, 0x2a, 0x5b, 0x77, 0xe7, 0xec, 0xa2,
	0x55, 0xfb, 0x79, 0xd1, 0x6a, 0xa6, 0x52, 0x73, 0xa9, 0x75, 0x76, 0x12, 0x31, 0x19, 0x73, 0x6a,
	0x06, 0xd1, 0x3b, 0xc8, 0x69, 0x3a, 0x7e, 0x0d, 0x69, 0xaf, 0x69, 0x93, 0x5e, 0xcd, 0x05, 0x1d,
	0xcf, 0x72, 0xfc, 0x27, 0xe4, 0x2e, 0x67, 0x82, 0xf1, 0x21, 0x4f, 0xdc, 0x85, 0x94, 0x63, 0x5f,
	0xcb, 0x6d, 0xaf, 0xb3, 0xd4, 0xdb, 0x70, 0x62, 0x17, 0xb5, 0x7d, 0x94, 0xd0, 0x43, 0x4f, 0xaf,
	0xf0, 0xd4, 0x9d, 0xc7, 0x8a, 0x0b, 0x9e, 0x67, 0x64, 0x33, 0x83, 0x52, 0x6a, 0x66, 0x12, 0xc3,
	0x38, 0x54, 0xc3, 0xea, 0x17, 0x32, 0x3d, 0xd1, 0xc1, 0x0d, 0x34, 0x35, 0x9c, 0x7a, 0x6c, 0xc5,
	0x2e, 0x6a, 0xfe, 0x63, 0xd2, 0x10, 0x94, 0x43, 0xa2, 0x41, 0x8d, 0x58, 0xfa, 0xef, 0x57, 0xac,
	0xe0, 0x7c, 0xfd, 0x4a, 0x3b, 0xb2, 0xd2, 0x6c, 0xc2, 0x6f, 0x49, 0x1b, 0x1d, 0x0a, 0x72, 0xa6,
	0x8d, 0xb2, 0x63, 0xe3, 0xac, 0x7a, 0x8a, 0x82, 0xe1, 0x5e, 0x04, 0xab, 0x78, 0xe3, 0x76, 0xc5,
	0xf5, 0xe6, 0xb0, 0x03, 0x26, 0x0e, 0x2e, 0x21, 0xff, 0x25, 0x69, 0x62, 0x50, 0x09, 0x22, 0x63,
	0x22, 0xff, 0xbf, 0x6b, 0x82, 0x19, 0x41, 0x85, 0x1c, 0x5a, 0x62, 0xb1, 0xf3, 0x88, 0x6c, 0x28,
	0x28, 0xe8, 0x18, 0x54, 0xa2, 0x0d, 0x55, 0xce, 0x17, 0xdc, 0x44, 0xdb, 0xba, 0x93, 0x8e, 0x2a,
	0x05, 0x0d, 0x2f, 0x76, 0xff, 0x7c, 0x6b, 0x79, 0x9f, 0x7f, 0x7f, 0x7f, 0x78, 0x6f, 0xb6, 0xe8,
	0xa7, 0x0b, 0xab, 0x6e, 0xb7, 0xb2, 0xfb, 0xfc, 0x6c, 0x12, 0x7a, 0xe7, 0x93, 0xd0, 0xfb, 0x35,
	0x09, 0xbd, 0x2f, 0xd3, 0xb0, 0x76, 0x3e, 0x0d, 0x6b, 0x3f, 0xa6, 0x61, 0xed, 0x43, 0xf3, 0x6a,
	0x9f, 0x19, 0x97, 0xa0, 0xfb, 0x75, 0x5c, 0xef, 0xa7, 0x7f, 0x03, 0x00, 0x00, 0xff, 0xff, 0x2e,
	0x45, 0x9b, 0x33, 0x46, 0x03, 0x00, 0x00,
}

func (this *Params) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*Params)
	if !ok {
		that2, ok := that.(Params)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if this.BridgeEnabled != that1.BridgeEnabled {
		return false
	}
	if this.BridgeOutEnabled != that1.BridgeOutEnabled {
		return false
	}
	if this.GatewayAccount != that1.GatewayAccount {
		return false
	}
	if !this.BridgeConfirmationThreshold.Equal(that1.BridgeConfirmationThreshold) {
		return false
	}
	if this.MinimumBridgeAmount != that1.MinimumBridgeAmount {
		return false
	}
	if this.MaximumBridgeAmount != that1.MaximumBridgeAmount {
		return false
	}
	if this.DepositTimeoutBlocks != that1.DepositTimeoutBlocks {
		return false
	}
	if this.NameServiceEnabled != that1.NameServiceEnabled {
		return false
	}
	if this.NameRegistrationMinMillisteem != that1.NameRegistrationMinMillisteem {
		return false
	}
	if this.NamePendingTimeoutBlocks != that1.NamePendingTimeoutBlocks {
		return false
	}
	if this.RelayerStartBlock != that1.RelayerStartBlock {
		return false
	}
	return true
}
func (m *Params) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Params) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Params) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.RelayerStartBlock != 0 {
		i = encodeVarintParams(dAtA, i, uint64(m.RelayerStartBlock))
		i--
		dAtA[i] = 0x58
	}
	if m.NamePendingTimeoutBlocks != 0 {
		i = encodeVarintParams(dAtA, i, uint64(m.NamePendingTimeoutBlocks))
		i--
		dAtA[i] = 0x50
	}
	if m.NameRegistrationMinMillisteem != 0 {
		i = encodeVarintParams(dAtA, i, uint64(m.NameRegistrationMinMillisteem))
		i--
		dAtA[i] = 0x48
	}
	if m.NameServiceEnabled {
		i--
		if m.NameServiceEnabled {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x40
	}
	if m.DepositTimeoutBlocks != 0 {
		i = encodeVarintParams(dAtA, i, uint64(m.DepositTimeoutBlocks))
		i--
		dAtA[i] = 0x38
	}
	if m.MaximumBridgeAmount != 0 {
		i = encodeVarintParams(dAtA, i, uint64(m.MaximumBridgeAmount))
		i--
		dAtA[i] = 0x30
	}
	if m.MinimumBridgeAmount != 0 {
		i = encodeVarintParams(dAtA, i, uint64(m.MinimumBridgeAmount))
		i--
		dAtA[i] = 0x28
	}
	{
		size := m.BridgeConfirmationThreshold.Size()
		i -= size
		if _, err := m.BridgeConfirmationThreshold.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintParams(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x22
	if len(m.GatewayAccount) > 0 {
		i -= len(m.GatewayAccount)
		copy(dAtA[i:], m.GatewayAccount)
		i = encodeVarintParams(dAtA, i, uint64(len(m.GatewayAccount)))
		i--
		dAtA[i] = 0x1a
	}
	if m.BridgeOutEnabled {
		i--
		if m.BridgeOutEnabled {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x10
	}
	if m.BridgeEnabled {
		i--
		if m.BridgeEnabled {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func encodeVarintParams(dAtA []byte, offset int, v uint64) int {
	offset -= sovParams(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *Params) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.BridgeEnabled {
		n += 2
	}
	if m.BridgeOutEnabled {
		n += 2
	}
	l = len(m.GatewayAccount)
	if l > 0 {
		n += 1 + l + sovParams(uint64(l))
	}
	l = m.BridgeConfirmationThreshold.Size()
	n += 1 + l + sovParams(uint64(l))
	if m.MinimumBridgeAmount != 0 {
		n += 1 + sovParams(uint64(m.MinimumBridgeAmount))
	}
	if m.MaximumBridgeAmount != 0 {
		n += 1 + sovParams(uint64(m.MaximumBridgeAmount))
	}
	if m.DepositTimeoutBlocks != 0 {
		n += 1 + sovParams(uint64(m.DepositTimeoutBlocks))
	}
	if m.NameServiceEnabled {
		n += 2
	}
	if m.NameRegistrationMinMillisteem != 0 {
		n += 1 + sovParams(uint64(m.NameRegistrationMinMillisteem))
	}
	if m.NamePendingTimeoutBlocks != 0 {
		n += 1 + sovParams(uint64(m.NamePendingTimeoutBlocks))
	}
	if m.RelayerStartBlock != 0 {
		n += 1 + sovParams(uint64(m.RelayerStartBlock))
	}
	return n
}

func sovParams(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozParams(x uint64) (n int) {
	return sovParams(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *Params) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowParams
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Params: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Params: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field BridgeEnabled", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.BridgeEnabled = bool(v != 0)
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field BridgeOutEnabled", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.BridgeOutEnabled = bool(v != 0)
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field GatewayAccount", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthParams
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthParams
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.GatewayAccount = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field BridgeConfirmationThreshold", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthParams
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthParams
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.BridgeConfirmationThreshold.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 5:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field MinimumBridgeAmount", wireType)
			}
			m.MinimumBridgeAmount = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.MinimumBridgeAmount |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 6:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field MaximumBridgeAmount", wireType)
			}
			m.MaximumBridgeAmount = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.MaximumBridgeAmount |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 7:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field DepositTimeoutBlocks", wireType)
			}
			m.DepositTimeoutBlocks = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.DepositTimeoutBlocks |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 8:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field NameServiceEnabled", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.NameServiceEnabled = bool(v != 0)
		case 9:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field NameRegistrationMinMillisteem", wireType)
			}
			m.NameRegistrationMinMillisteem = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.NameRegistrationMinMillisteem |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 10:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field NamePendingTimeoutBlocks", wireType)
			}
			m.NamePendingTimeoutBlocks = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.NamePendingTimeoutBlocks |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 11:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field RelayerStartBlock", wireType)
			}
			m.RelayerStartBlock = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.RelayerStartBlock |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipParams(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthParams
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipParams(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowParams
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowParams
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowParams
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthParams
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupParams
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthParams
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthParams        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowParams          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupParams = fmt.Errorf("proto: unexpected end of group")
)
