// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: steemvm/steembridge/v1/withdrawal.proto

package types

import (
	cosmossdk_io_math "cosmossdk.io/math"
	fmt "fmt"
	_ "github.com/cosmos/gogoproto/gogoproto"
	proto "github.com/cosmos/gogoproto/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// WithdrawalStatus is the status of a withdrawal. A withdrawal is an immutable
// bridge-out request record (asteem already burned); there is no on-chain
// relay/completion flow, so REQUESTED is the only status.
type WithdrawalStatus int32

const (
	WithdrawalStatus_WITHDRAWAL_STATUS_REQUESTED WithdrawalStatus = 0
)

var WithdrawalStatus_name = map[int32]string{
	0: "WITHDRAWAL_STATUS_REQUESTED",
}

var WithdrawalStatus_value = map[string]int32{
	"WITHDRAWAL_STATUS_REQUESTED": 0,
}

func (x WithdrawalStatus) String() string {
	return proto.EnumName(WithdrawalStatus_name, int32(x))
}

func (WithdrawalStatus) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_38df08baffdf45e0, []int{0}
}

// Withdrawal defines the Withdrawal message.
type Withdrawal struct {
	Id                      uint64                `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Sender                  string                `protobuf:"bytes,2,opt,name=sender,proto3" json:"sender,omitempty"`
	DestinationSteemAccount string                `protobuf:"bytes,3,opt,name=destination_steem_account,json=destinationSteemAccount,proto3" json:"destination_steem_account,omitempty"`
	AmountAsteem            cosmossdk_io_math.Int `protobuf:"bytes,4,opt,name=amount_asteem,json=amountAsteem,proto3,customtype=cosmossdk.io/math.Int" json:"amount_asteem"`
	AmountMillisteem        uint64                `protobuf:"varint,5,opt,name=amount_millisteem,json=amountMillisteem,proto3" json:"amount_millisteem,omitempty"`
	Memo                    string                `protobuf:"bytes,6,opt,name=memo,proto3" json:"memo,omitempty"`
	BurnTxHash              string                `protobuf:"bytes,7,opt,name=burn_tx_hash,json=burnTxHash,proto3" json:"burn_tx_hash,omitempty"`
	Status                  WithdrawalStatus      `protobuf:"varint,8,opt,name=status,proto3,enum=steemvm.steembridge.v1.WithdrawalStatus" json:"status,omitempty"`
	CreatedAt               uint64                `protobuf:"varint,9,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
}

func (m *Withdrawal) Reset()         { *m = Withdrawal{} }
func (m *Withdrawal) String() string { return proto.CompactTextString(m) }
func (*Withdrawal) ProtoMessage()    {}
func (*Withdrawal) Descriptor() ([]byte, []int) {
	return fileDescriptor_38df08baffdf45e0, []int{0}
}
func (m *Withdrawal) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Withdrawal) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Withdrawal.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Withdrawal) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Withdrawal.Merge(m, src)
}
func (m *Withdrawal) XXX_Size() int {
	return m.Size()
}
func (m *Withdrawal) XXX_DiscardUnknown() {
	xxx_messageInfo_Withdrawal.DiscardUnknown(m)
}

var xxx_messageInfo_Withdrawal proto.InternalMessageInfo

func (m *Withdrawal) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Withdrawal) GetSender() string {
	if m != nil {
		return m.Sender
	}
	return ""
}

func (m *Withdrawal) GetDestinationSteemAccount() string {
	if m != nil {
		return m.DestinationSteemAccount
	}
	return ""
}

func (m *Withdrawal) GetAmountMillisteem() uint64 {
	if m != nil {
		return m.AmountMillisteem
	}
	return 0
}

func (m *Withdrawal) GetMemo() string {
	if m != nil {
		return m.Memo
	}
	return ""
}

func (m *Withdrawal) GetBurnTxHash() string {
	if m != nil {
		return m.BurnTxHash
	}
	return ""
}

func (m *Withdrawal) GetStatus() WithdrawalStatus {
	if m != nil {
		return m.Status
	}
	return WithdrawalStatus_WITHDRAWAL_STATUS_REQUESTED
}

func (m *Withdrawal) GetCreatedAt() uint64 {
	if m != nil {
		return m.CreatedAt
	}
	return 0
}

func init() {
	proto.RegisterEnum("steemvm.steembridge.v1.WithdrawalStatus", WithdrawalStatus_name, WithdrawalStatus_value)
	proto.RegisterType((*Withdrawal)(nil), "steemvm.steembridge.v1.Withdrawal")
}

func init() {
	proto.RegisterFile("steemvm/steembridge/v1/withdrawal.proto", fileDescriptor_38df08baffdf45e0)
}

var fileDescriptor_38df08baffdf45e0 = []byte{
	// 413 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x92, 0x41, 0x6f, 0xd3, 0x30,
	0x14, 0xc7, 0x93, 0x52, 0x02, 0x7d, 0x1a, 0x53, 0xb1, 0x60, 0x18, 0xa6, 0xa5, 0x11, 0x17, 0x22,
	0x90, 0x12, 0x8d, 0x89, 0x0b, 0x27, 0x52, 0xad, 0xd2, 0x26, 0xc1, 0x81, 0x24, 0x53, 0x25, 0x2e,
	0x96, 0x1b, 0x5b, 0x8d, 0x45, 0x1d, 0x4f, 0xb1, 0xdb, 0x95, 0x6f, 0xc1, 0xc7, 0xda, 0x71, 0x47,
	0xc4, 0x61, 0x42, 0xed, 0x97, 0xe0, 0x88, 0xe2, 0x84, 0x31, 0x10, 0x27, 0x3f, 0xbf, 0xff, 0xef,
	0xff, 0xfc, 0xf4, 0xfc, 0xe0, 0x85, 0x36, 0x9c, 0xcb, 0x95, 0x8c, 0xed, 0x39, 0xab, 0x05, 0x9b,
	0xf3, 0x78, 0x75, 0x18, 0x5f, 0x08, 0x53, 0xb2, 0x9a, 0x5e, 0xd0, 0x45, 0x74, 0x5e, 0x2b, 0xa3,
	0xd0, 0x5e, 0x07, 0x46, 0xb7, 0xc0, 0x68, 0x75, 0xf8, 0xec, 0xd1, 0x5c, 0xcd, 0x95, 0x45, 0xe2,
	0x26, 0x6a, 0xe9, 0xe7, 0x3f, 0x7b, 0x00, 0xd3, 0x9b, 0x12, 0x68, 0x17, 0x7a, 0x82, 0x61, 0x37,
	0x70, 0xc3, 0x7e, 0xda, 0x13, 0x0c, 0xed, 0x81, 0xa7, 0x79, 0xc5, 0x78, 0x8d, 0x7b, 0x81, 0x1b,
	0x0e, 0xd2, 0xee, 0x86, 0xde, 0xc2, 0x53, 0xc6, 0xb5, 0x11, 0x15, 0x35, 0x42, 0x55, 0xc4, 0x3e,
	0x45, 0x68, 0x51, 0xa8, 0x65, 0x65, 0xf0, 0x1d, 0x8b, 0x3e, 0xb9, 0x05, 0x64, 0x8d, 0x9e, 0xb4,
	0x32, 0x1a, 0xc3, 0x03, 0x2a, 0x9b, 0x88, 0x50, 0xeb, 0xc3, 0xfd, 0x86, 0x1f, 0x1f, 0x5c, 0x5e,
	0x8f, 0x9c, 0xef, 0xd7, 0xa3, 0xc7, 0x85, 0xd2, 0x52, 0x69, 0xcd, 0x3e, 0x47, 0x42, 0xc5, 0x92,
	0x9a, 0x32, 0x3a, 0xad, 0x4c, 0xba, 0xd3, 0x7a, 0x12, 0x6b, 0x41, 0xaf, 0xe0, 0x61, 0x57, 0x43,
	0x8a, 0xc5, 0x42, 0xb4, 0x75, 0xee, 0xda, 0xb6, 0x87, 0xad, 0xf0, 0xe1, 0x26, 0x8f, 0x10, 0xf4,
	0x25, 0x97, 0x0a, 0x7b, 0xb6, 0x2f, 0x1b, 0xa3, 0x00, 0x76, 0x66, 0xcb, 0xba, 0x22, 0x66, 0x4d,
	0x4a, 0xaa, 0x4b, 0x7c, 0xcf, 0x6a, 0xd0, 0xe4, 0xf2, 0xf5, 0x09, 0xd5, 0x25, 0x7a, 0x07, 0x9e,
	0x36, 0xd4, 0x2c, 0x35, 0xbe, 0x1f, 0xb8, 0xe1, 0xee, 0xeb, 0x30, 0xfa, 0xff, 0x60, 0xa3, 0x3f,
	0xe3, 0xcb, 0x2c, 0x9f, 0x76, 0x3e, 0x74, 0x00, 0x50, 0xd4, 0x9c, 0x1a, 0xce, 0x08, 0x35, 0x78,
	0x60, 0xbb, 0x1b, 0x74, 0x99, 0xc4, 0xbc, 0x3c, 0x82, 0xe1, 0xbf, 0x56, 0x34, 0x82, 0xfd, 0xe9,
	0x69, 0x7e, 0x72, 0x9c, 0x26, 0xd3, 0xe4, 0x3d, 0xc9, 0xf2, 0x24, 0x3f, 0xcb, 0x48, 0x3a, 0xf9,
	0x78, 0x36, 0xc9, 0xf2, 0xc9, 0xf1, 0xd0, 0x19, 0xbf, 0xb9, 0xdc, 0xf8, 0xee, 0xd5, 0xc6, 0x77,
	0x7f, 0x6c, 0x7c, 0xf7, 0xeb, 0xd6, 0x77, 0xae, 0xb6, 0xbe, 0xf3, 0x6d, 0xeb, 0x3b, 0x9f, 0xf6,
	0x7f, 0x2f, 0xc8, 0xfa, 0xaf, 0x15, 0x31, 0x5f, 0xce, 0xb9, 0x9e, 0x79, 0xf6, 0xb7, 0x8f, 0x7e,
	0x05, 0x00, 0x00, 0xff, 0xff, 0x93, 0xcd, 0x4c, 0xf3, 0x46, 0x02, 0x00, 0x00,
}

func (m *Withdrawal) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Withdrawal) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Withdrawal) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.CreatedAt != 0 {
		i = encodeVarintWithdrawal(dAtA, i, uint64(m.CreatedAt))
		i--
		dAtA[i] = 0x48
	}
	if m.Status != 0 {
		i = encodeVarintWithdrawal(dAtA, i, uint64(m.Status))
		i--
		dAtA[i] = 0x40
	}
	if len(m.BurnTxHash) > 0 {
		i -= len(m.BurnTxHash)
		copy(dAtA[i:], m.BurnTxHash)
		i = encodeVarintWithdrawal(dAtA, i, uint64(len(m.BurnTxHash)))
		i--
		dAtA[i] = 0x3a
	}
	if len(m.Memo) > 0 {
		i -= len(m.Memo)
		copy(dAtA[i:], m.Memo)
		i = encodeVarintWithdrawal(dAtA, i, uint64(len(m.Memo)))
		i--
		dAtA[i] = 0x32
	}
	if m.AmountMillisteem != 0 {
		i = encodeVarintWithdrawal(dAtA, i, uint64(m.AmountMillisteem))
		i--
		dAtA[i] = 0x28
	}
	{
		size := m.AmountAsteem.Size()
		i -= size
		if _, err := m.AmountAsteem.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintWithdrawal(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x22
	if len(m.DestinationSteemAccount) > 0 {
		i -= len(m.DestinationSteemAccount)
		copy(dAtA[i:], m.DestinationSteemAccount)
		i = encodeVarintWithdrawal(dAtA, i, uint64(len(m.DestinationSteemAccount)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.Sender) > 0 {
		i -= len(m.Sender)
		copy(dAtA[i:], m.Sender)
		i = encodeVarintWithdrawal(dAtA, i, uint64(len(m.Sender)))
		i--
		dAtA[i] = 0x12
	}
	if m.Id != 0 {
		i = encodeVarintWithdrawal(dAtA, i, uint64(m.Id))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func encodeVarintWithdrawal(dAtA []byte, offset int, v uint64) int {
	offset -= sovWithdrawal(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *Withdrawal) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Id != 0 {
		n += 1 + sovWithdrawal(uint64(m.Id))
	}
	l = len(m.Sender)
	if l > 0 {
		n += 1 + l + sovWithdrawal(uint64(l))
	}
	l = len(m.DestinationSteemAccount)
	if l > 0 {
		n += 1 + l + sovWithdrawal(uint64(l))
	}
	l = m.AmountAsteem.Size()
	n += 1 + l + sovWithdrawal(uint64(l))
	if m.AmountMillisteem != 0 {
		n += 1 + sovWithdrawal(uint64(m.AmountMillisteem))
	}
	l = len(m.Memo)
	if l > 0 {
		n += 1 + l + sovWithdrawal(uint64(l))
	}
	l = len(m.BurnTxHash)
	if l > 0 {
		n += 1 + l + sovWithdrawal(uint64(l))
	}
	if m.Status != 0 {
		n += 1 + sovWithdrawal(uint64(m.Status))
	}
	if m.CreatedAt != 0 {
		n += 1 + sovWithdrawal(uint64(m.CreatedAt))
	}
	return n
}

func sovWithdrawal(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozWithdrawal(x uint64) (n int) {
	return sovWithdrawal(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *Withdrawal) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowWithdrawal
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Withdrawal: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Withdrawal: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Id", wireType)
			}
			m.Id = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowWithdrawal
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Id |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Sender", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowWithdrawal
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthWithdrawal
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthWithdrawal
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Sender = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field DestinationSteemAccount", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowWithdrawal
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthWithdrawal
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthWithdrawal
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.DestinationSteemAccount = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field AmountAsteem", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowWithdrawal
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthWithdrawal
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthWithdrawal
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.AmountAsteem.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 5:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field AmountMillisteem", wireType)
			}
			m.AmountMillisteem = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowWithdrawal
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.AmountMillisteem |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Memo", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowWithdrawal
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthWithdrawal
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthWithdrawal
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Memo = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 7:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field BurnTxHash", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowWithdrawal
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthWithdrawal
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthWithdrawal
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.BurnTxHash = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 8:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Status", wireType)
			}
			m.Status = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowWithdrawal
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Status |= WithdrawalStatus(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 9:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field CreatedAt", wireType)
			}
			m.CreatedAt = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowWithdrawal
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.CreatedAt |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipWithdrawal(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthWithdrawal
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipWithdrawal(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowWithdrawal
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowWithdrawal
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowWithdrawal
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthWithdrawal
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupWithdrawal
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthWithdrawal
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthWithdrawal        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowWithdrawal          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupWithdrawal = fmt.Errorf("proto: unexpected end of group")
)
